index.rst, javarosa.rst
No need to merge, as far as I’m concerned, but I would appreciate feedback.
=> Start documenting JavaRosa

getting-started.rst
Addresses comments by on #30 by @ronna 
also, closes #19
=> fix sd card warning and change phone to devices

contributing.rst, index.rst
In re: issue #22 
This is the first swing at a contributor guide, but a lot more is needed so I'm not closing it.
- Specifically, a guide to actually WRITING in rst/sphinx markup. I'll do that next, and close the issue then.
- Also a *writing style* guide would be good too, but - I think is probably a different issue.
---
This guide deals with a lot of setup and installation issues which can be fussy. Also, I am a Mac person, so there are probably things here that don't apply or would need to be different.
Anyone with Linux or Windows expertise is encouraged to fork and add/fix.
=> Contributing

contributing.rst, getting-started.rst
Expands contributor guide with detailed instructions on Sphinx and reStructured text.
closes #22 
I would appreciate someone who does not know Sphinx well to read this and let me know if it is clear.
=> Writing guide

contributing.rst, ss.py
- script for getting screenshots and saving them correctly into docs source
- adds info on android tools to contrib guide
- adds info on using screenshot script to contrib guide
=> Screenshot scripting

circle.yml
It would seem that Sphinx magically creates an _images folder and puts images (but not other binary files there). This will fix the problem, but I'm not sure if this PR is a good idea, and that's why it's WIP.
=> WIP: Upload _images to CloudFront

img/form-widgets/select-search-start.png
recreated the image and ran it through imageoptim
closes #77
=> fix broken png

collect-forms.rst
This pull request addresses https://github.com/opendatakit/docs/issues/96. 
I fixed the spelling mistakes in the collect-forms.rst file.
=> Fixes the spelling mistakes in collect-forms.rst

README.md, contributing.rst
Added the following information:
1. about commit messages
2. Python 3 compatibility
3. branches
also fixed typing issues
=> Added more info in contributing file and fixed typing errors

_templates/footer.html
Fixes #104 
@adammichaelwood  Done :)
=> Display page title on footer buttons (Issue #104)

contributing.rst, glossary.rst, javarosa.rst
This PR fixes few spelling mistakes.
=> Fixes spelling mistakes.

collect-forms.rst
@adammichaelwood I have added some info which I thought was missing in the doc. Are these additions correct? Plus, is there a separate doc needed for these explanations?
=> Added extra info about lists (Issue #114)

_static/css/custom.css, _templates/footer.html, conf.py
Please find the attached screenshot which reflects the changes. I didn't put the links and text in a single variable though because for some reason the linking wasn't working. However now the links and texts are stored in the conf.py.
=> Swaps the navigate buttons with the file an issue notice.

collect-install.rst, collect-settings.rst, contributing.rst
Made minor fix in contributing.rst
=> fix-issue #96

collect-forms.rst
Android Developer Bridge ---> Android Debug Bridge
=> adb full form 

_static/css/custom.css, _templates/footer.html
Made the footer buttons responsive
=> fix-issue #129

getting-started.rst, glossary.rst
=> Line edits

_static/css/custom.css
Styles matched for `guilabel` and `menuselection`.
Addresses #109
=> Matching styles for guilabel and menuselection

_templates/footer.html, conf.py
Added Feedback Mechanism
closes #62
=> Adds link to forum in doc footer

briefcase-forms.rst, briefcase-guide.rst, briefcase-install.rst, index.rst
Added guide about installation and usage of briefcase
Closes #136
=> Adds Briefcase guide

_templates/footer.html, conf.py
=> Fixed variable names in conf.py

briefcase-vs-aggregate.rst, index.rst
=> Added differences between Briefcase and Aggregate

_templates/footer.html, conf.py
=> Fixed footer link

briefcase-vs-aggregate.rst
Made some changes in  briefcase-vs-aggregate.rst file.
This PR addresses #96
=> made changes in briefcase-vs-aggregate.rst

contributing.rst
=> Adb for windows

contributing.rst
Add info to complete adb installation for windows.
Closes #189
=> Adds information on Adb installation for windows users

contributing.rst
This is tested and was shown in [git help ](https://help.github.com/articles/configuring-a-remote-for-a-fork/)
Closes #208
=> Git windows

contributing.rst
closes https://github.com/opendatakit/docs/issues/204
Updated the build command and added a tip to use the utility script.
Adds a tip and updates the build command.
=> Updated build command and tip for using b.sh added

form-widgets.rst, img/form-widgets/barcode1.png
closes #183 
Update the barcode scanner screenshot.
=> screenshot updated

briefcase-install.rst
closes #212 
Updates the java version from 7 to 8 which is recommended in the Briefcase installation guide.
=> Fixed java version

getting-started.rst
addresses #28
I added links of a few tutorial videos out of almost all the ODK tutorial videos on youtube which I found the most reliable and useful.
=> Added links of  training videos in getting started guide.

aggregate-guide.rst, aggregate-install.rst, aggregate-use.rst
addresses #96 
Fixed minor typos in aggregate-guide.rst, aggregate-install.rst and aggregate-use.rst.
=> Fixed minor typos

index.rst, pyxform.rst
closes #7 
Documentation on pyxform 
A suitable place has to be found for this doc
=> added documentation on pyxform

encrypted-forms.rst, index.rst
=> Added documentation on encrypted forms

.github/PULL_REQUEST_TEMPLATE.md
closes #214 
I changed the unclear question to:
What new issues will need to be opened because of this PR?
=> edit pr template

collect-install.rst
addresses #96  
Made some changes to collect-install.rst file.
=> Fixed Punctuation Marks

README.md
Simple steps for building and viewing the docs once one's environment is set up. The contribution guide is fantastic for getting started but too detailed to use as a reference. This addition means those familiar with Sphinx can quickly get up and running and those who have gone through the contribution guide can get a quick reminder.
=> Add run instructions

.github/ISSUE_TEMPLATE.md
addresses #226
A template for creating issues
=> Added Issue template

faq.rst, index.rst
I moved faq section in the old docs to the new docs. 
closes #192
=> adds faq section 

collect-settings.rst, img/collect-settings/admin-settings.jpeg, img/collect-settings/form-management.jpeg, img/collect-settings/general-settings.jpeg, img/collect-settings/main-menu.jpeg, img/collect-settings/server-settings.jpeg, img/collect-settings/ui-settings.jpeg, img/collect-settings/und-settings.jpeg
closes #54  and   #6 
- Explained the general settings , admin settings and the main menu options.
- Added screenshots wherever needed
- Added notes and warning as needed
=> Documented admin settings, general settings and main menu.

aggregate-guide.rst, collect-guide.rst, index.rst, xlsform.rst
closes #248 
Pulled in the doc as specified in the issue. Made some changes to it by removing/fixing links that timed out or were broken. Referenced different sections of the docs as needed. 
Once the PR regarding form-design doc is merged, update the link of the form-design documentation. At the moment it refers to https://opendatakit.org/help/form-design/guidelines/.
=> XLSForm introduction added.

collect-settings.rst, encrypted-forms.rst, faq.rst
addresses #96 
Fixed typos in faq.rst, encrypted-forms.rst and collect-settings.rst.
=> Fixed typos

index.rst, security-privacy.rst, xlsform.rst
closes #255 
Pulled in the doc, made references to the sections in the documentation and formatted.
Updating the links as references to our own documentation sections as they're merged.
=> Pulled the Security and Privacy doc.

cygwin.rst, img/cygwin/pip-install.png, img/cygwin/python-path.png
closes # 159
Update the previous document about setting up Docs under Windows with Cygwin.
Some typos and edit sentences
=> Enhance cygwin doc

form-uploader.rst, index.rst
closes #253 
Documentation on Form Uploader
=> Added documentation on Form Uploader

collect-adb.rst, collect-forms.rst, collect-guide.rst, collect-install.rst, encrypted-forms.rst, getting-started.rst
addresses #261 
Updated external links as references to doc.
=> Updated external links

img/download-verify/cmd-verify.png, img/download-verify/copy-signature.png, img/download-verify/not-verified.png, img/download-verify/sha256-signatures.png, img/download-verify/terminal-verify.png, img/download-verify/verified.png, index.rst, verify-downloads.rst
closes #245 
Download Verification process is added.
Verification on Mac is not done.
=> Added Download Verification doc

aggregate-limitations.rst, index.rst
closes #26 
Added limitations of Aggregate and issues with different versions.
=> Added limitations of Aggregate

aggregate-deployment-planning.rst, aggregate-install.rst, briefcase-guide.rst, index.rst, security-privacy.rst
closes #250 
Pulled in Aggregate document-planning doc and updated references.
=> Added doc for Aggregate deployment planning

contributing-tips.rst, encrypted-forms.rst, faq.rst, glossary.rst, security-privacy.rst, verify-downloads.rst
addresses #96 
minor line edits to several docs
I didn't go through every document so there are possibly more edits to be made.
=> line edits to several docs.

aggregate-install.rst
closes #11 
- Added expected errors while installing Aggregate on App Engine.
- Added link to example log.
=> Added expected errors while installing Aggregate

aggregate-use.rst
addresses #96 
Fixed minor typos in Aggregate-use
=> Line edit for aggregate-use

aggregate-deployment-planning.rst
closes #
addresses #
Https reference for ODK Briefcase was provided earlier and now reference has been changed to the ODK Briefcase doc.
No new issues
=> http reference is changed in documentation

aggregate-use.rst
addresses #261 
Updated external link to OAuth2 service in Aggregate usage guide.
=> Updated link for OAuth2 info

contributing.rst
closes #276 
Added information about redirect process in contributor guide in case of renaming a file.
=> Documented page redirect process

aggregate-use.rst, oauth2-service.rst
addresses #96 
Minor corrections in aggregate-use.rst and oauth2-service.rst.
=> Line edit for Aggregate use guide and oauth2-service

collect-settings.rst
closes #114 
Clarifies the usage of view sent forms option.
=> Clarify view sent form option.

_static/css/custom.css, aggregate-install.rst, aggregate-upgrade.rst, img/aggregate-upgrade/dropdown.png, img/aggregate-upgrade/find-version.png, img/aggregate-upgrade/search-logs.png, img/aggregate-upgrade/select-project.png, index.rst
closes #228 
- Added need for upgrading Aggregate
- Added upgrade steps and release notes for Aggregate
- Added upgrade admonition for Upgrade notes
=> Added upgrade guide for Aggregate

aggregate-guide.rst, aggregate-install.rst, aggregate-upgrade.rst, briefcase-vs-aggregate.rst
addresses #96 
Minor line edits for Briefcase and Aggregate docs.
=> Line edits for Briefcase and Aggregate docs

_static/css/custom.css, contributing.rst
closes #305 
- Added wrap and unwrap class.
- Added default wrap for rst code-blocks.
- Added note on using wrap and unwrap classes.
=> Fix overflow lines in code-blocks

collect-settings.rst, img/collect-settings/form-management.png, img/collect-settings/form-management2.png, img/collect-settings/image-settings.png
=> Added Information on image size settings

form-interaction.rst, index.rst
closes #97 
Added interaction of constraints, relevants and read only fields in forms.
=> Added information on using constraints, relevants and read only

contributing.rst
closes #320 
Updated contributor's guide with instructions on how to add inline images.
=> updated contributor's guide to add informaation about inline images.

collect-forms.rst, img/collect-forms/jumpbutton.png, img/collect-forms/jumpicon.png, img/collect-forms/jumpmenu.png, img/collect-forms/jumpscreen.png
closes #186 
Added information about jump button in the "filling a form" section.
=> Describe jump button. 

img/collect-forms/jumpmenu.png, img/collect-forms/jumpscreen.png
closes #323
two png images with bad color profile were fixed, 
to address a problem with pngquant
We *might* want to think about adding a note on this in the contrib guide.
=> fixes png color profile 

contributing.rst, downloads/form-interaction/example_1.xlsx, downloads/form-interaction/example_1.xml, downloads/form-interaction/example_2.xlsx, downloads/form-interaction/example_2.xml, form-interaction.rst
closes #47
- Added `downloads` directory to place downloadable files in.
- Added information on using `:download:` directive in contributor guide.
- Added downloadable files for example forms in `form-interaction.rst`.
=> Added directory for downloadable files and information on adding them 

img/odk-build/about.png, img/odk-build/add-translation.png, img/odk-build/collapse-question.png, img/odk-build/display-language.png, img/odk-build/download-xml.png, img/odk-build/edit-menu.png, img/odk-build/file-menu.png, img/odk-build/form-properties.png, img/odk-build/help-menu.png, img/odk-build/information-text.png, img/odk-build/instance-name.png, img/odk-build/open-form.png, img/odk-build/properties.png, img/odk-build/remove-prompt.png, img/odk-build/remove-translation.png, img/odk-build/rename.png, img/odk-build/sign-in.png, img/odk-build/translations.png, img/odk-build/upload-form.png, img/odk-build/view-menu.png, index.rst, odk-build.rst
closes #322 
Added guide on ODK Build and its usage.
=> Added doc on ODK Build

aggregate-backup.rst, conf.py, img/aggregate-backup/admin.png, img/aggregate-backup/backup-form.png, img/aggregate-backup/backup-info.png, img/aggregate-backup/backup-job.png, img/aggregate-backup/backup-list.png, img/aggregate-backup/backup-select.png, img/aggregate-backup/cloud-console.png, img/aggregate-backup/disable-writes.png, img/aggregate-backup/dropdown.png, img/aggregate-backup/email-select.png, img/aggregate-backup/enable-admin.png, img/aggregate-backup/enable-writes.png, img/aggregate-backup/open-admin.png, img/aggregate-backup/pending-backup.png, img/aggregate-backup/project-select.png, img/aggregate-backup/restore-backup.png, img/aggregate-backup/restore-job.png, img/aggregate-backup/restore-status.png, index.rst
closes #101 
- Added backup information from Briefcase.
- Added backup information from SQL dump.
- Added backup information from GAE.
=> Added Aggregate-backup guide

contributing.rst
addresses #96 
Fixed a typo that I came across while reading the screenshot section in `contributing.rst`.
=> fix a typo

collect-forms.rst
closes #14 
Added a note which explains the behavior of cell when an empty value is sent.
=> Documented the behavior of cells when empty values are sent

collect-settings.rst
closes #315
closes opendatakit/collect#1575
addresses #302
**What is included in this PR?**
Adds more detail on the image size setting. Proposes an alternate way to display feature versions.
=> Update image size setting description.

collect-settings.rst, img/collect-settings/import-settings.jpg, img/collect-settings/share-icon.jpg
closes #107 
Elaborated the import/export settings by adding more information about the QR codes.
=> Elaborated on QR codes

collect-settings.rst, img/collect-settings/form-metadata.png
=> Updated information on form metadata username

form-widgets.rst, img/form-widgets/ethiopian-start.png, img/form-widgets/ethiopian2.png, img/form-widgets/ethiopian3.png
closes #338 
Information on Ethiopian calendar form widget
=> Added information on Ethiopian calendar form widget

conf.py, contributing.rst
=> Added global substitutions

_static/css/custom.css
closes #364 
Fixed figure caption style.
=> Fixed style of figure captions

index.rst
Two small changes to the index to add precision. Both are described in greater detail in the commits.
=> Index changes

getting-started.rst
Change descriptions are in each commit.
=> Getting started tweaks

briefcase-api.rst, index.rst
closes #375 
addresses #380 
Pulled in Briefcase API doc.
=> Added Briefcase API doc

.gitignore, conf.py, form-widgets.rst, video.py
closes #66 
- Added video directive for sphinx
- Modified form-widgets.rst to use this directive
I am not sure whether the options like width, height, etc are required with this directive. I will add the options as required.
There are very few tutorials for creating a sphinx directive and they don't really clear the basics. I referred some of the tutorials and other extensions to create the video directive.
=> Added video directive

collect-filling-forms.rst, form-widgets.rst
closes #387 
- Used video directive in place of raw html
- Added alt content for videos
=> Replaced raw html with video directive

aggregate-install.rst
closes #355 
addresses #380 
Added complete information on Aggregate aws install
=> Added complete info on aws install

collect-connect-google.rst, img/collect-connect/server-settings-google-account-modal.png
closes #377 
- Updated instructions for selecting Google account
- Updated image of selecting Google account
=> Updated Collect Google Drive setup instructions

_static/css/custom.css
closes #362 
- Fixed style of menuselection text role in toc. 
- Style of guilabel is not retained in toc so no fix for that.
=> Fixed style of menuselection in toc

launch-apps-from-collect.rst
I realized that it actually is possible to use the field-list population feature from XLSForm. Added that and fixed some unclear language.
=> Improve external app instructions.

_static/css/custom.css, contributing.rst
closes #410 
- Added comments and organized css
- Added info on adding custom css in contributors guide
=> Organized custom css 

collect-filling-forms.rst, img/collect-completing-forms/choose-language.png, img/collect-completing-forms/question-screen-highlight-change-language.png, img/collect-completing-forms/save-partial-filled-form.png, img/collect-completing-forms/saveicon.png
closes #417 
- Added info on changing form language
- Added info on saving partially filled form
=> Updated info on language change and saving partially filled form

contributing.rst
closes #388 
Added information on using video directive in contributors guide.
=> Added info on using video directive

collect-settings.rst
closes #5 
Added info on saving and loading external settings
=> Added info on external settings in Collect

collect-settings.rst, img/collect-settings/form-entry-settings.png, img/collect-settings/main-menu-settings.png, img/collect-settings/moving-backwards-disabled.png, img/collect-settings/moving-backwards-enabled.png, img/collect-settings/user-settings.png, img/collect-settings/user-settings2.png
closes #365 
closes #412 
- Documented moving backwards settings
- Adde images for user interface settings
=> Documented moving backwards settings in Collect

aggregate-backup.rst, aggregate-deployment-planning.rst, aggregate-increase-aws-size.rst, aggregate-setup.rst, aggregate-upgrade.rst
closes #431 
The toctree in aggegregate-setup is reordered, and the page titles for documents included in that toc have been updated to use gerunds. I also fixed a typo and changed the underlining style for section titles in one file.
=> Reorders agg setup

aggregate-app-engine.rst
closes #437 
- Removed step 28 and added the Allow image in step 21.
- Add info on project settings in step 7.
=> Fix App-engine install steps

contributing.rst
closes #
addresses #96 
My first PR w/ ODK ;-)
Changed line 1525, adding a hyphen for "docs-related issue".
Not a problem, exactly. I'm using Atom, and on my first attempted save it automatically removed trailing whitespace in 48 places in the 'contributing.rst' doc. Maybe that's not a bad thing in general, but to err on the safe side, I turned this function off, refreshed from master, and then made my change once again.
I'm here because of Adam's talk at Berkeley WeWork last week. Well done!
=> Line edit 96

style-test.py
closes #481 
Index is compared with line length before adding a character to line.
=> Adds index checking

style-guide/check-space.py
addresses #471 
Regex checks for a uppercase and a lowercase character after a period for the spacing check.
=> Improved check for spacing

style-test.py
closes #491 
- Include untracked files while checking.
- Remove deleted files from check list.
=> Fix for diff option

src/collect-forms.rst, src/collect-install.rst
closes #454 
fixes three titles to gerunds that should have been fixed earlier
=> Make collect procedures gerunds

src/docs-syntax-guide.rst, src/docs-tech-guide.rst
closes #505 
- Update build instructions.
- Update location of ``vid``, ``img`` and ``downloads``.
=> Fix instructions in contributors guide

src/aggregate-data-access.rst, src/form-widgets.rst, src/img/form-widgets/acknowledge.png
addresses #96 
Spelling fixes in reference to https://github.com/opendatakit/docs/pull/522#issuecomment-365758402
=> Spelling fixes

style-test.py
closes #526 
Added encoding to ``style-test.py``
=> Added encoding

src/form-update.rst
closes #507 
Added a note on having same filenames when generating newer versions of form.
=> Add note on filenames to form update guide

src/form-widgets.rst
addresses #96
I corrected a minor grammatical error.  I corrected 'can not' to read 'cannot' in the Form Widgets doc.
I was not able to get the document review with Sphinx to work from my GitBash command line in Windows, so I was unable to check the appearance of my correction.  I will work on this issue.
=> Corrected 'can not' to read 'cannot'

src/docs-tech-guide.rst
=> Capitalize and remove stray char

src/docs-developer-guide.rst, src/docs-style-guide.rst, src/docs-tech-guide.rst, src/spelling_wordlist.txt
closes #468 
closes #529 
- Added info on style guide testing
- Added info on adding style guide checks
- Added info on spell checking
=> Add info on style guide testing and spell checking

src/collect-offline-maps.rst, src/collect-settings.rst, src/collect-using.rst
Closes #3 
I hesitated on where to put this in the TOC. It's not a tip or best practice. It feels like an extension of settings but doesn't fit well on the settings page so that's how it ended up where I put it.
=> Add instructions for using offline maps

src/collect-adb.rst
closes #56 
addresses #402 
New section in collect-adb, with info on pulling debug logs.
Also, while I was there, I did some cleanup on the rest of the file.
=> Adds info about using adb to get error logs and other diagnostics

src/briefcase-using.rst
Minor tweaks from my review of #540
=> Briefcase guide tweaks

src/form-widgets.rst
closes #565 
All the XML blocks are removed from form-widgets.rst
=> Remove xml from form widgets

.circleci/config.yml
I tested this command manually to confirm it works.
=> Enable ODK 2

odk1-src/validate.rst
closes #360 
addresses #402 
Rewrite of Validate page.
=> rewrites Validate

odk1-src/form-interaction.rst
closes #24 
A warning section in the form-interaction doc covering the issue and a workaround
=> adds warning about calculation relevance

odk1-src/aggregate-vm.rst
closes #579 
New content for Docs » Setting Up ODK Aggregate » Installing Aggregate » ODK Aggregate Virtual Machine with updated information about downloading, installing and configuring an ODK Aggregate VM.
We will have to fix the OVA download URL whenever ODK Aggregate v.1.5.0 is released
Leaving this section while we figure out if this PR is ready
Leaving this section while we figure out if this PR is ready
=> Adds documentation for ODK Aggregate VM

odk1-src/aggregate-vm.rst
* Removed irrelevant content (e.g., warnings about reading the docs and warning about setting a FQDN).
* Added more generic download link
* Added clarity (IMHO) to section headers
* Used my judgement to re-arrange tips and notes
=> Edit for clarity

odk2-src/advanced-topics-developer.rst, odk2-src/build-scripts.rst
closes #591 
Adds a brief overview of the build system for the ODK 2 Android tools, and the Gradle Config repository.
=> Add documentation for gradle scripts

.github/PULL_REQUEST_TEMPLATE.md
A few more `#` to make the PR text easier to read.
=> Make text easier to read

odk1-src/aggregate-upgrade.rst
Closes #629
Aggregate v1.0 is quite old (2011) and not terribly relevant
=> Aggregate 1.0 is 5 years old and not relevant

odk1-src/launch-apps-from-collect.rst
Closes #651
Just a wee lil rename
=> Renaming title

odk1-src/briefcase-using.rst
closes #654
- Add an important remark of a change starting with version 1.9.0
- Moved "how to get help" up 
- Fixed existing commands by adding the operation param
- Added new sections for the push and clear prefs operations
- Improved the section about the export operation
- Minor adjustments of the RST formatting of headers
=> Issue 654 Refresh and improve docs on Briefcase CLI

odk1-src/form-logic.rst
Closes #655 
I struggled with explaining the concept of joining repeats to their parent and why that's difficult. Suggestions very welcome!
=> Repeat warning

.gitignore
* I use pyenv, so wanted to add that to the ignore
* Added comments so we know what is being ignored
* Added minor tweak to emacs ignore. Stolen from https://github.com/github/gitignore/blob/master/Global/Emacs.gitignore#L3
* Controversial? Removed style-checks.py and extra.py. If they are important, they maybe should be in the repo? If they are not important, they should be elsewhere?
=> Improve ignore

odk1-src/aggregate-data-access.rst
closes #641
A note explaining how often Aggregate will publish submissions under certain conditions.
=> Issue 641 Add note about how often Aggregate publishes

odk1-src/form-question-types.rst
closes #678 
Info on how to do the choices list, 
including the detail that name can't have spaces.
=> add details on list choices

odk1-src/briefcase-using.rst, odk1-src/img/briefcase-using/pull-in-parallel.png
closes #25 
A note in briefcase-using about enabling the parallel connections setting.
=> adds note on parallel connections

odk1-src/openrosa-authentication.rst, odk1-src/openrosa-form-list.rst
closes #422
adds labels to openrosa-authentication
(contra the issue description, most of the OR pages had labels. Just that one didn't.)
=> add labels to open rosa auth

odk1-src/form-question-types.rst
closes #617 
Small section on including "or_other" as an option.
=> add section on or_other

odk1-src/form-logic.rst
=> Describe when form expressions are evaluated

odk1-src/form-logic.rst, odk1-src/form-operators-functions.rst
addresses #660 
addresses #686
Fixing escapes, minor grammar issues, and warning about misuse
=> Add warnings to functions

odk1-src/form-language.rst, odk1-src/img/form-language/colors-english.png, odk1-src/img/form-language/colors-spanish.png, odk1-src/index.rst, odk1-src/vid/form-language/language-switch.mp4, shared-src/spelling_wordlist.txt
closes #611 
New doc on form localization.
=> form localization

odk1-src/form-language.rst
Addresses #672
Minor language clean up and clarify potential confusion about where localization happens
I spent way too much time coming up with the right language and placement. It's not perfect, but I think it's good enough.
=> Clarify potential confusion about where localization happens

odk1-src/pyxform.rst
closes #307 
Added a tip in pyxform doc.
=> added tip on quick form pushing

odk1-src/security-privacy.rst
closes #461 
- removed headline numbers
- added section labels
- added on-page contents
- light edits
This doc is old. Someone who knows more should do a close reading for current facts.
=> light edits on security-privacy doc

odk1-src/form-question-types.rst
closes #445 
Very little.
I just added the question type under location widgets section,
with a minimal description and link to their site.
An example *might* have been a good idea.
But.... I decided it wasn't worth the trouble,
as nothing I could write would lessen the need for a user to go read the OMK docs.
I tried to come up with a simple example.... 
The OMK docs, though, are not great. 
So I ended up not being able to do much besides linking to them.
=> adds openmapkit question type

odk1-src/printer-widget.rst
=> intentname is not a word

odk1-src/incl/form-examples/sum-to-count-responses.rst
closes #713 
addresses #96 
fixes the double-equals comparison operators in a form example
=> fixes double equals in form repeats

odk1-src/getting-started.rst, odk1-src/index.rst
closes #455 
Moved the section about how ODK gets used to the home page,
and cleaned up Getting Started for style, better internal links, and clearer procedure.
=> Edits getting started

odk1-src/form-question-types.rst
closes #704 
Added a `tip` about the satellite count and elapsed time.
=> adds note about geopoint dialog

odk1-src/form-logic.rst
closes #702 
Just a note about not using quote marks in default values.
=> adds note about quotes in default values

odk1-src/collect-settings.rst, odk1-src/img/collect-settings/dark-theme-main-menu.png, odk1-src/img/collect-settings/light-theme-main-menu.png, odk1-src/img/collect-settings/ui-settings.png
closes #718
- Updates the image for UI settings
- adds a settings section for Theme
I tried to make the side-by-side images figures with captions,
but they did not display side-by-side as expected. 
Since the captions weren't completely necessary, 
I switched to images instead.
But I'm opening an issue for this,
because it would be nice to have side-by-side figures sometimes.
There's a broken ref link in this branch,
in `form-styling.rst`,
which should have been caught in a previous PR test.
I'm wondering what is going wrong that we aren't catching it.
=> adds details on dark theme

shared-src/docs-tech-guide.rst
Absolutely tiny first change. Fixed a link that wasn't working on render.
=> Fixed link to Python 3

odk2-src/app-designer-install.rst, odk2-src/suitcase-install.rst, odk2-src/survey-install.rst, odk2-src/tables-install.rst
Addresses #755
I checked to see if these links went to the correct binaries. I did not build this and see if this actually shows in a web browser.
=> Fix links to ODK 2 binaries

odk1-src/aggregate-app-engine.rst, odk1-src/aggregate-tomcat.rst
closes #730 
Updated links to the JDK for both App Engine and Tomcat installs.
=> Jdk link added to GAE and tomcat docs for ODK Aggregate

odk1-src/conf.py
closes #571 
Additional Sphinx commands to integrate github with Sphinx. Easy PR creation is our friend :)
=> github integration for odk docs

odk2-src/conf.py
closes #571 
Adds Github Integration for ODK2 docs.
=> github integration for odk2 docs

odk1-src/form-question-types.rst
Closes #751
New documentation for the `max-pixels` feature.
=> Add new doc for max-pixels image parameter

odk1-src/form-question-types.rst
Confirmed working through local build
=> Extra space causes table to render incorrectly

odk1-src/getting-started.rst
Addresses https://forum.opendatakit.org/t/certificate-on-aggregate-sandbox-server-expired/14045
Confirmed working by building site and confirming the links work.
=> Updated sandbox to not require port

odk1-src/collect-forms.rst
Remove  formstate results so our title looks consistent
=> Adding formstate results in an inconsistent title

odk1-src/collect-connect.rst, odk1-src/collect-sms-submissions.rst, odk1-src/collect-using.rst
partially addresses #781
First pass at SMS docs.
Some of the components described in #781 will need to be expanded on. All screenshots of Server settings will need to be updated.
It's hard to know where this should be linked from and how it should be split up. Perhaps the form design part should go in form design, for example. 
CC @jd-alexander
=> Add basic docs for SMS submission

.circleci/config.yml, Makefile
Closes #787 
Addresses #788
* Ensure sure the Docker image has make
* Persist the Makefile
=> PDF make fix

.circleci/config.yml, Makefile
closes #787
Adds make command for odk1 and odk2 pdf build.
=> Added make commands for pdf build

odk1-src/index.rst
* List tools we update
* Remove deprecated tools
* Link to specs and APIs
* Add a prominent link to getting started
=> List current tools, add links to getting started

shared-src/faq.rst
Related issue: https://github.com/opendatakit/docs/issues/261
closes #
addresses #
=> Update FAQ with better getting started doc pointers

odk1-src/aggregate-tomcat.rst
Related issue: https://github.com/opendatakit/docs/issues/261
closes #
addresses #
=> Removed link to /use and edited networking section

Makefile, README.md
Replace underscores with hyphens. Not sure how this snuck in there, but it seems like we should standardize on one way of doing things. I confirmed that the commands are only used in the Makefile and in the README.
=> Standardize on hyphens

odk1-config/s3_website.yml
Sort and remove unneeded slashes.
Related: [Broken window theory](https://en.wikipedia.org/wiki/Broken_windows_theory) of software development.
=> Sort and remove unneeded slashes

odk1-src/glossary.rst, odk2-src/glossary.rst
Addresses #795 
Removal of text from both glossaries
=> Form Uploader has been deprecated

odk1-src/form-logic.rst
closes #738 
Fixed references for now, random, once
=> fix function path references

.gitignore, Makefile, README.md, requirements.txt, tests/test_style_guide.py
closes #818 
This PR stubs out a very basic foundation for testing Python code using the hypothesis test framework. It also adds a new make target for running the tests.
=> Adds the basis for testing Python code using the hypothesis framework.

odk1-src/aggregate-upgrade.rst
Addresses #809
Upgrade notes on wiki have been moved to each release, so the link isn't needed
=> Upgrade notes on wiki have been moved

odk1-src/aggregate-tomcat.rst
Closes #770
* Clean up whitespace
* Use sentence case
* Move security note to the security section
* Add minimum version information. 
I start with v1.4.13 because that's when MS/Azure SQL, Tomcat 8, MySQL 5.7, and PostgreSQL 9.4 were added, so it's a [known checkpoint](https://github.com/opendatakit/aggregate/releases/tag/v1.4.13_Production). I toyed with the idea of adding a v1.5.0 header, but I'm pretty sure the minimum versions are the same.
I say _should_ in my prose because we haven't verified.
=> Add version information for Aggregate

shared-src/_templates/layout.html
Closes #188
Add location hash to Analytics. Learned about this at https://stackoverflow.com/questions/4811172/is-it-possible-to-track-hash-links-like-pages-with-google-analytics
=> Track anchor links

odk1-src/central-forms.rst, odk1-src/central-intro.rst, odk1-src/central-submissions.rst, odk1-src/img/central-forms/attachments-listing.png, odk1-src/img/central-forms/attachments-multi.png, odk1-src/img/central-forms/attachments-overview.png, odk1-src/img/central-forms/attachments-single.png, odk1-src/img/central-submissions/listing.png
closes #830 
Changes to:
* Intro: updating supported features and adding performance notes
* Submissions: screenshot and text for new submissions table
* Forms: screenshots and sections for form attachments
=> central: update overview, forms, submissions docs for block 2 release.

requirements.txt
Addresses #822
* Looked at the [theme changelog](https://sphinx-rtd-theme.readthedocs.io/en/latest/changelog.html) to make sure there is nothing that would break break the site.
* Clicked through the site to make sure the site looked like the site
@adammichaelwood, I'm hoping you can do a better sanity check here.
=> Upgrading the theme to get a better font stack

odk1-src/central-command-line.rst, odk1-src/central-intro.rst, odk1-src/index.rst
Neutral language about how early Central is without having alpha/beta everywhere
=> Central is now in beta, but is ready for production use

odk1-src/central-setup.rst, odk1-src/central-upgrade.rst
Add link to upgrade instructions because users might not know to go to GH.
=> Add link to upgrade instructions

odk1-src/collect-filling-forms.rst
closes #856 
One change, word changed from "geolocation" to "location"
=> Change word "geolocation" to "location"

odk1-src/collect-intro.rst
closes #855 
Changed the word "geolocation" to "location"
=> Update word "geolocation" to "location"

odk1-src/collect-install.rst
Closes #864
* Description of the permissions requested by Collect and why
* Instructions for granting or denying multiple permissions from Settings
=> Document permissions requested and how to grant all

odk1-src/briefcase-install.rst, odk1-src/briefcase-using.rst, odk1-src/collect-import-export.rst, odk1-src/img/briefcase-intro/briefcase-pull.png, odk1-src/img/briefcase-using/pull-in-parallel.png, odk1-src/incl/briefcase-features.rst
Closes #795, #733, #711, #703
I've reviewed the main Briefcase section to update it with things that have changed since v1.9
=> Update docs about Briefcase

odk1-src/briefcase-using.rst
Addresses https://github.com/opendatakit/briefcase/pull/649
* Match shipping code
=> Briefcase split select multiples

odk1-src/briefcase-intro.rst
Closes #883.
This edits the opening blurb on the ODK Briefcase page that introduces ODK Briefcase.
=> Improve the opening sentence of the ODK Briefcase introduction page.

Makefile, README.md, run-task.bat, run-task.sh
Closes #868
- Adds polling to detect file changes and trigger builds in all supported host operating systems.
- Adds a pair of scripts (Linux/macOS and Windows) to launch Makefile tasks with the Docker container.
- Adds a section to the README file explaining how to work in the docs using the Docker container.
Tested in Linux (Ubuntu 18.04) and Windows 10
=> Improve Docker tools

README.md
This PR adds some context around the local installation options. When I first read the updated README, it wasn't clear to me which option I should pick and why. I also tried to make things a little friendlier to someone who has no idea with Docker, git, etc are. Fundamentally, I think this remains a pretty technical process but at least we don't need to deal with version problems.
@ggalmazor did I frame things reasonably? If you're happy with it, please merge. If you want some tweaks, I'm happy for you to push changes directly to my branch.
=> Add context around the new Docker install/run process

odk1-config/s3_website.yml, odk1-src/aggregate-backup.rst, odk1-src/aggregate-upgrade.rst, odk1-src/briefcase-and-aggregate.rst, odk1-src/briefcase-using.rst, odk1-src/img/briefcase-using/pull-in-parallel.png, odk1-src/incl/briefcase-features.rst
Addresses #842 
Closes #531
* Better match the Briefcase UI
* Adding some language explaining what a CLI is
* Minor spelling fixes
* Clarify that CLI only sends blank form if it doesn't exist https://github.com/opendatakit/docs/issues/703
* Dramatically improved screenshot 😂 (and yes, it was compressed!)
* Re-arrange some of the features in order of importance
=> Briefcase copy edits

shared-src/docs-syntax-guide.rst
=> Fix broken links missed in switch to Docker build

odk1-src/aggregate-admin.rst, odk1-src/encrypted-forms.rst, odk2-src/scan-form-designer-using.rst, odk2-src/survey-form-processing.rst, odk2-src/xlsx-converter-reference.rst
Line edits
Edits for latin abbreviations such as i.e. and e.g. in favor of preferred: "for example", "for instance", or "such as" where appropriate.
=> Edits for latin abbreviations

odk1-src/form-operators-functions.rst
Addresses #893 by providing hint about why we use 1970
=> Standardize on date format, provide hint about why we use 1970

odk1-src/briefcase-using.rst, shared-src/spelling_wordlist.txt
closes #897 
This PR includes a new section that explains how Briefcase logs work.
=> Issue 897 briefcase logs

odk1-src/aggregate-vm.rst
Closes #866
Improved instructions that work with Aggregate master.
Marked as WIP because we want to merge this after the Aggregate release.
=> More detailed instructions to get VM working

odk1-src/aggregate-app-engine.rst, odk1-src/aggregate-deployment-planning.rst, odk1-src/oauth2-service.rst
Closes #850
Add language in the places where a user would look to install Aggregate on GAE.
It would be good to ask if the community has been able to set up new servers without a credit card.
=> Google Cloud now requires a credit card or bank account

requirements.txt
=> Fix for CVE-2018-18074

odk1-src/briefcase-using.rst
Consistency issues with a list of bullet points on what was line 148. Fixed to be consistent, now is on line 147
=> line edit: fix consistency issue with bullet points

odk1-src/form-question-types.rst
=> Prevent support questions from users with old versions

odk1-src/form-question-types.rst
Closes #923
* Added required upcoming versions of Collect/Aggregate with dynamic seeds
* Clarified that integer is required
* Added a more realistic example
This is a little weird because the versions aren't out yet. But if the text looks correct, I think we should merge and then at least people will know randomize isn't working because their versions will be wrong.
=> Improve rand example

odk1-src/aggregate-data-access.rst
Generic language because the limits are always going up. Sheets can now support 5 million cells.
=> Generic language because the limits are always going up

odk1-src/briefcase-using.rst
closes #929
Fixed Briefcase UI export conf param label
=> Reduce GeoJSON label in Briefcase export docs

odk1-src/briefcase-using.rst
closes #927 
Documentation about the new Briefcase UI export conf param introduced in https://github.com/opendatakit/briefcase/pull/692
=> Add new UI export conf param

odk2-src/app-designer-overview.rst, odk2-src/sync-endpoint.rst
fix: launch Page Button does not exist in application designer.
fix: added a instruction on how to get to phpLDAPadmin page on computer.
N/A
N/A
N/A
=> Documentation fix on Sync Endpoint and Application Designer

odk2-src/getting-started-2-architect.rst, odk2-src/survey-sample-app-install.rst, odk2-src/survey-sample-app-navigate-form.rst
closes #
addresses
Various grammar fixes and adding periods to bullets, along with a wording change here and there
Looked at deployment architect getting started guide, and ODK Survey User Guide
Probably a lot of other little stuff like this across all the docs
=> grammar, wording, and punctuation

odk2-src/getting-started-2-user.rst
=> updating the user start guide with correct describtion

odk1-src/form-question-types.rst
closes #951 
None.
Nothing.
None.
=> Adds type and appearance for date and time widget with year appearance

odk1-src/aggregate-deployment-planning.rst
=> Minor grammar fix

odk1-src/form-question-types.rst
closes #941 
Add documentation for media files as choices for select questions.
None.
None.
None.
=> Document media files as choices

odk1-src/collect-filling-forms.rst, odk1-src/form-language.rst, odk1-src/form-logic.rst, odk1-src/form-question-types.rst
Addresses #950
* Tried to standardize language around repeats
* Cross-link heavily
=> Jump screen stuff tweaks

odk2-src/app-designer-install.rst, odk2-src/app-designer-prereqs.rst, odk2-src/getting-started-2-user.rst
closes #
addresses #
Added a warning to ubuntu users and added some extra instructions for the PATH variable and actually starting app designer.
=> App Designer Setup

odk2-src/getting-started-2-user.rst
closes #
addresses #
Added clarification for what an aggregate server is/what it's used for in the getting started user guide.
=> clarification on aggregate

odk1-src/briefcase-using.rst, odk1-src/img/briefcase-using/start-pull-from-last-submission-pulled.png
closes #967
New info about the new Briefcase feature introduced in opendatakit/briefcase#698
=> Issue 967 add briefcase pull start from last submission pulled info

odk1-src/form-audit-log.rst
Closes #934
* Removed unnecessary commas and spaces
* Added a section on location tracking that describes how it's enabled and the implementation
* Added example output with explanations of columns
* Updated table with new events
**Reviewers**
Please pay close attention to description of location-priority values, the description of how the implementation works, and the description of the new events. If there are recommended values for the various variables, please suggest them.
=> Add location tracking

odk1-src/aggregate-do.rst
Closes https://github.com/opendatakit/aggregate/issues/428
* Default to the console since every one will have that. Then add links to SSH
* Remove the brackets from the certbot command. People *should* be able to know that that they should replace the uppercase.
=> Remove {} and use web console instead of SSH

odk1-src/form-audit-log.rst
=> Add location usecase

odk2-src/getting-started-2-architect.rst
If you did not trust your computer on your device, "$ grunt adbpush" won't work.
closes #
addresses #
=> Add clarification of potential errors.

odk1-src/form-question-types.rst, odk1-src/img/form-widgets/bikram-sambat-calendar-widget.png, shared-src/spelling_wordlist.txt
addresses #900 
The pr adds bikram-sambat appearance for dates.
=> Add bikram-sambat appearance for dates

odk1-src/collect-connect-google.rst
closes #976 
The pr just document limits in spreadsheets.
=> Document spreadsheet limits

odk1-src/collect-connect.rst, odk1-src/collect-install.rst, odk1-src/collect-sms-submissions.rst, odk1-src/collect-using.rst
Closes #781
* Comment out any links to SMS sending and add orphan tag to prevent build errors
* Add a warning to page in case someone has linked directly
I was not able to confirm that the warning shows up, so I'd love a reviewer to check that.
=> Document disable SMS sending

odk1-src/form-question-types.rst, odk1-src/img/form-widgets/selfie-video-widget-recorded.png, odk1-src/img/form-widgets/selfie-video-widget-recording.png, odk1-src/img/form-widgets/selfie-video-widget.png
closes #982 
It documents selfie video widget.
=> Document selfie video widget

odk1-src/form-question-types.rst
closes #509 
It adds link to All Widgets Google Doc.
=> Add link to All Widgets Google Doc

odk2-src/app-designer-overview.rst
=> Delete back button related documentation

odk1-src/form-operators-functions.rst
closes #936 
addresses #
document substring-before(), substring-after() and translate() XPath functions which have been added to javaRosa
=> add substring-before() substring-after() translate()

odk1-config/s3_website.yml
May or may not work, but needs to be merged to try.
=> Fix ODK2/X redirects

odk1-config/s3_website.yml, odk1-src/conf.py, odk2-config/s3_website.yml
Addresses #999 
Verified by applying this config to prod. Sorry :(
=> Finalize redirects

README.md, shared-src/docs-tech-guide.rst
=>  Moved python documentation from technical guide to README

odk1-src/aggregate-aws.rst, odk1-src/aggregate-do.rst
* Updated AWS instructions (and confirmed they worked)
* Updated DO instructions to match the language
=> Update AWS instructions for Aggregate

odk1-src/aggregate-google-cloud.rst, odk1-src/aggregate-install.rst, odk1-src/aggregate-tomcat.rst
* Added instructions (and confirmed they worked)
=> Add Google Cloud install

odk1-src/collect-forms.rst
closes #994 
This pr clarifies which sheet in a spreadsheet is being filled during sending forms.
=> Clarified which sheet in a spreadsheet is filled

odk1-src/aggregate-do.rst
* Responding to https://forum.opendatakit.org/t/problem-installing-aggregate-v2-on-digitalocean/19060
* Renamed the OS to 18.04.x to hopefully let people know they can use whatever version. I checked with Google Cloud and AWS to make sure this problem doesn't exist there.
* Fixed the CloudConfig link and made sure the links in the other cloud providers are not broken.
* Fixed numbering in DO.
=> Fix bad link and update OS description

odk1-src/aggregate-aws.rst, odk1-src/aggregate-do.rst, odk1-src/aggregate-google-cloud.rst
We don't document the default username and password. We should!
I have confirmed that this renders nicely with the See Details
=> Add default passwords

odk1-src/briefcase-using.rst
closes #993
Updated CLI help block with the new -sfd flag
=> Update CLI help block for the pull operation

odk1-src/form-repeats.rst
closes #726
The pr just documents how to handle a repeat_count that may be decreased by the user.
=> Describe how to handle a repeat_count that may be decreased by the user

requirements.txt
* Narrow fix for https://nvd.nist.gov/vuln/detail/CVE-2019-10906
* Rebuild Docker image and made sure the site loads
=> Fix for CVE-2019-10906

odk1-src/aggregate-azure.rst, odk1-src/aggregate-install.rst, odk1-src/aggregate-tomcat.rst
* Instructions to install on AWS. Tried 2x to confirm working.
* Tried to match other cloud install language
=> Instructions for Microsoft Azure

odk2-src/survey-sample-app-install.rst
link removed since we only need to use the first two sentences of the linked documentation, it might be confusing to link the whole thing and the user might continue on without realizing that's not what they want to do.
closes #
addresses #
small change
=> small changes to clarity

odk1-src/form-question-types.rst
closes #853
It documents front appearance for barcode widget.
=> Document front appearance for barcode widget

odk1-src/form-audit-log.rst
closes #1031 
It just documents answer tracking in the audit file: https://github.com/opendatakit/collect/pull/3072
=> Document answer tracking in audit file

odk1-src/collect-import-export.rst
Updates languages and basemaps for Collect configuration.
=> Add language and basemap keys and values

odk1-src/collect-forms.rst
closes #1009 
The pr just documents how to work with forms shared with other users using Google Drive.
=> Document how to share forms with media files using Google Drive as a server

odk1-src/central-install-digital-ocean.rst, odk1-src/img/central-install/docker-app.png
DigitalOcean has updated the Create Droplet flow so that "One-click apps" are now referred to as "Marketplace".
closes #1047
Updates to both the text and the screenshot that references the "One-click apps" section.
=> Update DigitalOcean instructions for Central

odk1-src/img/central-install/docker-app.png
Smaller image and highlight the option to make it more obvious.
=> Reduce image size and highlight option

odk1-src/aggregate-aws.rst, odk1-src/aggregate-azure.rst, odk1-src/aggregate-digital-ocean.rst, odk1-src/aggregate-google-cloud.rst
Closes #1030.
I would love a review that confirms that:
1. Making this a tip not a warning is the right thing to do.
1. The placement in the docs is correct.
1. The language I use is consistent and the links are to useful places.
Here's what it looks like...
=> Warn about ips

odk1-src/form-question-types.rst, odk1-src/img/form-widgets/myanmar-calendar-widget.png
closes #1048 
The pr documents Myanmar calendar we added recently.
=> Document Myanmar calendar

odk1-src/validate.rst
Update the documentation to reflect the changes in opendatakit/validate#64
=> update Validate docs

odk1-src/aggregate-forms.rst, odk1-src/aggregate-limitations.rst, odk1-src/aggregate-upgrade.rst
addresses #96 , please review.
This PR fixes some minor grammatical typos.
=> Fixed grammatical typos

odk1-src/briefcase-install.rst, odk1-src/briefcase-intro.rst, odk1-src/briefcase-using.rst, odk1-src/img/briefcase-install/welcome.png, odk1-src/img/briefcase-intro/briefcase-pull.png, odk1-src/img/briefcase-intro/briefcase_v1.16.0_linux.png, odk1-src/img/briefcase-intro/briefcase_v1.16.0_macos.png, odk1-src/img/briefcase-intro/briefcase_v1.16.0_windows.png, odk1-src/img/briefcase-using/details_button.png, odk1-src/incl/briefcase-features.rst
closes #1062
All the changes needed for the release of Briefcase v1.16:
(copied from the issue)
- Added support for ODK Central
- Deprecated conf options: pull in parallel
- New conf options: max simultaneous HTTP connections
- New unified Linux look and feel
- Recommend using Java.net (OpenJDK) Java 11 to run Briefcase
=> Issue 1062 briefcase v1.16

odk1-src/form-operators-functions.rst
closes #760 , please review.
This PR deals with documenting the digest function in the Form Operators and Functions section.
=> Documented digest function

odk1-src/aggregate-field-length.rst
Adding a quick hint to make life easier for folks collecting geodata.
=> Provide a hint as to how many geopoints are in 16000

odk1-src/form-audit-log.rst, odk1-src/validate.rst
* Slightly more robust language about what Aggregate displays
* Match formatting of Briefcase CLI docs
* Document that we can validate multiple forms
=> Release tweaks

odk1-src/form-operators-functions.rst
Specifies valid values for the digest function parameters from https://www.w3.org/TR/xforms/#fn-digest.
=> Add valid options for digest function

odk1-src/briefcase-using.rst
This support issue comes up all the time. It's in the [Aggregate docs](https://docs.opendatakit.org/aggregate-data-access#exporting) but we should add to the Briefcase docs.
=> Warn about UTF-8 CSVs

odk1-src/form-question-types.rst, odk1-src/img/form-widgets/persian-calendar-widget.png
closes #1049 
It just documents perisan calendar we have added recently.
=> Document persian calendar

odk1-src/briefcase-using.rst, odk1-src/collect-forms.rst, odk1-src/img/collect-forms/send-finalized-change-view.png
=> Issue 1020 yaw

odk1-src/aggregate-app-engine.rst, odk1-src/aggregate-tomcat.rst, odk1-src/briefcase-install.rst, odk1-src/encrypted-forms.rst
Closes #1107
Confirmed this PR builds and the text and links look good.
=> Recommend OpenJDK 11 from AdoptOpenJDK

.circleci/config.yml, odkx-src/conf.py
Renaming was done in https://github.com/opendatakit/docs/pull/1118
closes #1121 
- Renames instances of `odk2` with `odkx` in the circleci config
- Same replace in conf.py
=> Modify circleci/config.yml to match ODK2 => ODKX renaming

odkx-src/sync-endpoint.rst
closes #1119
- Make reference in step 13 to "cloned repository" consistent with earlier steps
- Add pointer in step 10 to directory where `security.properties` lives
=> Minor doc clarifications

odk1-src/collect-settings.rst
closes #1124
Just a link from one section of the docs to the other that completes the loop.
=> Add link from metadata settings to metadata

odk1-src/collect-forms.rst
closes #1077 
It just documents that not blank values will be preceded by an apostrophe to avoid parsing them.
=> Raw values are sent from Collect to Google Sheets as of v1.23

odkx-src/getting-started-2-architect.rst
closes  #1130 
addresses #
I am doing my very first docs edit! So I did a simple edit to the description of the grunt wipe-data command, which had actually been documented already, so issue 98 in ODK-X can be closed.
=> Editing the description of grunt wipe-data to test docs editing.

odkx-src/xlsx-converter-using.rst
closes #
addresses # https://github.com/opendatakit/docs/issues/1146
What is included in this PR?
This is my attempt at documenting the async_assign functionality.  Feedback is appreciated!  Thanks!
=> Add in async_assign documentation

odkx-src/advanced-topics-architect.rst, odkx-src/advanced-topics-developer.rst, odkx-src/build-app.rst, odkx-src/getting-started-2-architect.rst, odkx-src/index.rst
closes #
addresses #1139 
Updates to the landing page and related pages for initial learning path. 
Good progress on landing issues, need to deal with references to Aggregate and demo server still.
=> New landing

odk1-src/central-forms.rst, odk1-src/central-intro.rst, odk1-src/central-setup.rst
For 76d5de9, I did not also make this change in central-submissions because that mention of Tableau is a little more innocuous.
=> Minor central docs tweaks

odk1-src/form-question-types.rst, odk1-src/img/form-widgets/likert_widget.png, shared-src/spelling_wordlist.txt
addresses #1135 
Added likert widget documentation
=> Adding likert widget documentation

odk1-src/launch-apps-from-collect.rst
=> Document what intent extra Collect uses from external apps

odk1-src/collect-forms.rst
closes #1151 
The pr just updates the paragraph about apostrophes in GS (cahnges implemented in Collect in opendatakit/collect#3462)
=> Updated the paragraph about apostrophes in GS

odk1-src/central-upgrade.rst
apologies if this is already noted somewhere.
also, will gladly close and resubmit this pull request if there's a better place in the docs for this.
i asked in Slack about getting the version of an installed Central and @yanokwa helpfully told me about this.
=> tip for getting Central version

shared-src/docs-tech-guide.rst
addresses #96
**What is included in this PR?**
I made 3 basic line edits in the technical guide. I corrected the name of the text editor Notepad++, and I fixed the URLs for the ODK docs. 
**What problems did you encounter?**
I received 15 warnings in my build step, mostly relating to the image files and unknown documents referred to in the syntax and style guides.
=> I made a few line edits.

odkx-src/build-app.rst
closes #861
Minor updates from [Pushing.and.Pulling.Files.9.1.18.CGK.docx](https://github.com/opendatakit/docs/files/2413546/Pushing.and.Pulling.Files.9.1.18.CGK.docx)
The last section in the aforementioned document is confusing (hence the draft PR). Pending clarification on which changes are needed for the _Troubleshooting_ section (if any).
=> Update pushing and pulling files (#861)

odkx-src/app-designer-overview.rst
closes #1188 
Fix the the build breaking style issue.
=> Fix heading length

odk1-src/collect-security.rst
=> fix typo - #96

odkx-src/build-app.rst
A small typo fix to a column used in ODK-X xlsx forms.
n/a
n/a
n/a
=> Fix typo in ODK-X build app

odk1-src/collect-import-export.rst, odk1-src/img/collect-settings/import-settings-scanner.png, odk1-src/img/collect-settings/import-settings.png
This PR is in conjunction with https://github.com/opendatakit/collect/pull/3743
Updates images for the UI of QR Scanner interface and updates documentation due to changes in positioning.
=> Update QRCode Import/Export Docs

odk1-src/central-install-digital-ocean.rst, odk1-src/central-upgrade.rst
* Remove space in DigitalOcean
* Explain that firewalls are not strictly necessary
* Suggest upstream network firewall
=> No space to DigitalOcean, add more firewall explanation

odk1-src/collect-filling-forms.rst, odk1-src/img/collect-forms/repeat-inline-add.png
Closes #1223 
Just an addition to the repeats section in form filling about the new button.
=> Add note on inline add button in Collect

odk1-src/form-question-types.rst
=> Update min Aggregate version for start-geopoint

odk1-src/form-question-types.rst
Closes #1243
https://gitlab.com/axet/android-audio-recorder/-/tree/master
I've verified that it responds to the necessary implicit intent to be launched by Collect. It supports pretty much any format someone would want, audio clipping, and various other nice things.
=> Recommend open source recorder app

odk1-src/collect-location.rst, odk1-src/form-question-types.rst, odk1-src/img/collect-best-practices/accuracy-mode.png, odk1-src/img/collect-best-practices/example-form.png, odk1-src/img/collect-best-practices/improve-accuracy-mode.png, odk1-src/img/collect-best-practices/improve-accuracy.png, odk1-src/img/collect-best-practices/location-off.png, odk1-src/img/collect-best-practices/location-on.png, odk1-src/img/collect-best-practices/location.png, odk1-src/img/collect-best-practices/mode.png, odk1-src/img/collect-best-practices/warning-message.png
Closes #1225
I tried to focus on generally-applicable principles and link out to docs for information that might change based on Android version.
=> Describe how to ensure accurate geolocation readings

odk1-src/central-install-digital-ocean.rst, odk1-src/central-install.rst, odk1-src/central-troubleshooting.rst
* Warning for the install elsewhere so it's more likely to be read. 
* AWS instructions a little easier to parse due to better whitespace.
* Reducing the overuse of Central
I have not rendered this locally!
=> Formatting improvements

src/central-backup.rst, src/central-intro.rst
I get the sense talking to some users that Google Drive is required and that makes them nervous. In this PR, I clarify that it is not required.
=> Clarify that Google Drive backup is not required

src/central-briefcase.rst, src/central-using.rst
See https://github.com/getodk/briefcase/pull/872
=> Document using Briefcase with Central

src/central-install.rst, src/getting-started.rst
* Match the language on the website about what Cloud offers,
* Drop the, IHMO, unnecessary language about DO and give an easy to find link.
=> Match website language, more direct DO link

src/central-install-digital-ocean.rst
This isn't a common action, so I've put it under Advanced. And to keep maintenance burden low, I link out to existing content.
=> Adding external storage to DO

src/form-operators-functions.rst
=> Add zero-arg variants to string functions

src/collect-import-export.rst, src/collect-settings.rst, src/form-question-types.rst, src/img/form-widgets/audio-playback.png, src/img/form-widgets/audio-start.png, src/img/form-widgets/built-in-recorder.png, src/spelling_wordlist.txt
addresses https://github.com/getodk/collect/projects/4#card-49212675
* Screenshot updated
* Description updated
* Section on quality parameter
* Section on using external apps
=> Update docs for audio changes

src/central-backup.rst, src/central-install-digital-ocean.rst, src/central-install.rst, src/central-submissions.rst, src/central-troubleshooting.rst, src/img/central-submissions/listing.png
Completes #1281
I can't push to @issa-tseng's branch because of gitlfs things I don't fully understand.
I ran the new image through ImageOptim. If I had more time I'd make a better screenshot but I think the important thing is to have most of the functionality shown.
I ran this locally.
=> Central v1.1

src/central-troubleshooting.rst
Changed from 64 chars to 32 chars
=> Smaller path to ensure the text wraps nicely

src/central-submissions.rst, src/img/central-submissions/excel-login.png
* I tried this with recent versions of Excel and Power BI.
* I matched the order in the previous screenshot.
* I ran image-optim on the png.
=> Up-to-date and explicit instructions for Excel and Power BI

src/aggregate-data-access.rst
Closes #443 (which is already closed, but this is nicer).
=> Add link to wiki with more detail on JSON publisher

src/central-install-digital-ocean.rst
Now that we have the email troubleshooting section and clear guidance that people need to use a transactional mail provider, I think configuring DKIM shouldn't be put so front and center.
=> Minimize configuring DKIM because it is not common

src/central-upgrade.rst
Describe new and old ways of getting version.
=> Update to demo server

src/form-audit-log.rst, src/form-question-types.rst
closes #1323
Added notes about mocked locations.
=> Add notes about mocked locations

src/launch-apps-from-collect.rst
closes #1320
Improved the section about populate multiple fields.
=> Improved the section about populate multiple fields

src/form-question-types.rst
Not sure how this passed our spell-checker..
=> Fix spelling

src/central-submissions.rst, src/central-upgrade.rst, src/xlsform.rst
Previous PR: ttps://github.com/getodk/docs/pull/1346/files
=> Clearer language from final review

src/form-logic.rst
Learned about this at https://stackoverflow.com/questions/50028545/double-quotes-in-csv-table-cell/50028811
=> Escape comma

src/central-backup.rst
=> Mention Direct Backups via API

src/form-question-types.rst
closes #1363
Removed quotes from audio quality parameters resulting in invalid survey.
=> Fix audio quality parameter example

src/central-install.rst
Found at https://gist.github.com/tertek/b228b9ab6ec42ee9ef42c613eec6b90d
=> Add Windows guidance

src/collect-import-export.rst
Add languages that Collect is now translated in.
=> Update language codes to reflect new languages

src/central-install-digital-ocean.rst
Closes https://github.com/getodk/docs/issues/1339
=> Customization of Enketo and spelling fix

src/form-regex.rst
=> XPath functions are case sensitive

src/collect-adb.rst
Merge if you are happy with it.
=> Grammar tweak

src/collect-projects.rst, src/img/collect-projects/project-settings-dialog.png
Work towards #1365
This adds docs for deleting and switching project and some more details on adding projects.
=> Add more details to Managing Projects page

src/central-setup.rst, src/central-upgrade.rst, src/central-usage-reporting.rst
Builds on top of https://github.com/getodk/docs/pull/1394.
=> Central v1.3 tweaks

src/collect-settings.rst, src/form-question-types.rst, src/img/collect-settings/dark-theme-main-menu.png, src/img/collect-settings/light-theme-main-menu.png, src/img/collect-settings/server-settings.png
closes #1405
Everything specified in the issue.
The settings docs are still pretty out of date (screenshots and navigation references mainly) after the addition of the Projects feature but I tried to focus only updating the things we've changed for v2021.3 here.
=> Add docs for Collect v2021.3

src/central-server-audits.rst
Doing https://github.com/getodk/docs/pull/1404#discussion_r736789293 because it's easier to do than to remember to do.
=> Match the Central UI

src/collect-configure.rst, src/collect-connect-google.rst, src/collect-connect.rst, src/collect-filling-forms.rst, src/collect-install.rst, src/collect-projects.rst, src/collect-settings.rst, src/collect-using.rst, src/img/collect-settings/form-management.png, src/img/collect-settings/form-management2.png, src/img/collect-settings/general-settings.png, src/img/collect-settings/project-display.png, src/img/collect-settings/settings.png, src/img/collect-settings/ui-settings.png
=> Update Collect docs for new first launch experience and updated settings structure

requirements.txt
Confirmed that the website loads in the Docker container. This should be very low risk. As long as the site generates HTML, we should be good to go.
=> Fix vulnerabilities reported by GH

src/collect-settings.rst, src/form-question-types.rst
closes #1424
I updated the docs about internal audio recorder used by default
=> Updated the docs about internal audio recorder

src/form-logic.rst
Closes #1370 
A bit hard to explain and there are likely exceptions but hopefully this provides enough context to get someone thinking along the right lines.
=> Recommend against last-saved in contexts other than defaults

src/docs-style-guide.rst, src/docs-syntax-guide.rst, src/glossary.rst, src/javarosa.rst, src/openrosa.rst, src/validate.rst
=> Clean up mentions of Aggregate

src/collect-offline-maps.rst, src/form-datasets.rst, src/form-question-types.rst, src/img/form-widgets/select-from-map.png
=> Select map

src/form-question-types.rst
=> Make explicit that external selects are like internal ones

src/collect-import-export.rst
=> Add details for building QR code and Python sample

src/collect-location.rst, src/form-question-types.rst, src/img/form-widgets/geopoint-dialog.png
=> Document new geopoint dialog and configuration

docs/collect-filling-forms.rst, docs/collect-forms.rst, docs/form-logic.rst, docs/incl/form-examples/regex-middle-initial.rst
Follow up to https://github.com/getodk/docs/pull/1492
When through all files in /img/ to identify phone screenshots, then went to the relevant rst to make the change.
=> Scale down more vertical images

docs/collect-import-export.rst, docs/collect-settings.rst, docs/img/collect-settings/ui-settings.png
closes #1473
Removed splash screen from settings.
=> Removed splash screen from settings

README.md
=> Remove Docker build and improve Python build

docs/central-install-digital-ocean.rst
addresses https://github.com/getodk/docs/issues/1502, https://github.com/getodk/docs/issues/1501, https://github.com/getodk/docs/issues/1503
extra instructions how to customise sentry on 1.5.3
=> digital-ocean/customize-sentry: update for 1.5.3

docs/central-install-digital-ocean.rst
addresses #1502, #1501, #1503
extra instructions how to disable sentry on 1.5.3
=> digital-ocean/disable-sentry: update for 1.5.3

docs/central-forms.rst
=> Add details to form update section

docs/central-install-digital-ocean.rst
=> Standardize how we call backend, add link, add Sentry subdomain support

docs/central-forms.rst
=> Fix syntax error

docs/launch-collect-from-app.rst
closes #1441 
I've added a note that looks like:
=> Document that Form Edit action returns instance uri

docs/form-question-types.rst
closes #1337 
I've added a warning with an explanation which looks like:
=> Add advice about including fallback options when using barcode questions

docs/conf.py
Update to domain that hasn't been blocked and is unlikely to be blocked.
=> Update domain name

docs/central-troubleshooting.rst
Confirmed working on a test install.
=> Improved database restore command

docs/central-datasets.rst
We've received some direct feedback from users on the forum and through personal channels. We've also heard and read how people are talking about this functionality.
This PR:
- Summarizes why this new functionality is experimental
- Capitalizes Central concepts more consistently
- Emphasizes Entities over Datasets
- Adds sections for easier scanning
=> Update Entities section based on feedback

docs/central-entities.rst
=> Segmentation will eventually come

docs/central-install-digital-ocean.rst, docs/central-upgrade.rst
=> Update upgrade instructions for v1.5.3 and v2022.3

docs/form-question-types.rst, docs/form-styling.rst
=> Document big-image

docs/central-backup.rst, docs/central-upgrade.rst
Minor follow-up to #1560 and #1563
I don't know what "recommend it only for specific use cases" referred to. At this point I think it's clear that we prefer full machine backups and managed database backups but that this is the only other alternative.
=> Minor upgrade updates

docs/form-logic.rst, docs/img/form-logic/named-repeat-jump.png, docs/img/form-logic/named-repeat-summary.png, docs/img/form-logic/repeat-jump.png, docs/img/form-logic/repeat-summary.png, docs/spelling_wordlist.txt
Closes https://github.com/getodk/docs/issues/376
Not really sure what to name the little location summary at the top of a question. I went with form location summary but happy for other ideas.
Ran images through imageoptim.
=> Add section on naming repeats to help with navigation

docs/form-logic.rst
=> Add paragraphs and image spacing

docs/form-question-types.rst, docs/img/form-question-types/selfie-video-widget-recorded.png, docs/img/form-question-types/selfie-video-widget-recording.png, docs/img/form-question-types/selfie-video-widget.png
closes #1583 
Removed selfie video widget from question types.
=> Removed selfie video widget from question types

docs/form-logic.rst
Fixing a small typo in this form.
=> Move expression to choice_filter

docs/collect-connect-google.rst, docs/collect-connect.rst, docs/collect-forms.rst, docs/collect-import-export.rst, docs/collect-install.rst, docs/collect-settings.rst, docs/collect-using.rst, docs/img/collect-forms/downloading-not-a-form.png, docs/img/collect-forms/get-blank-form-not-a-form.png, docs/img/collect-forms/get-forms-google.png, docs/img/collect-forms/not-form-exception.png
I made sure everything rendered properly. I also search for Drive, Sheets, Google to find candidates for removal/edits.
=> Remove Google Drive/Sheets

docs/form-datasets.rst, docs/form-question-types.rst, docs/img/form-question-types/select-from-map-point.png, docs/img/form-question-types/select-from-map-polygon.png, docs/img/form-question-types/select-from-map.png
This section is getting long so I added some headers and did a little bit of reorganization.
I got the polygons from OSM data. Maybe I should have used some simpler rectangles but I think for now this is ok.
=> Add polygons as mapped choices

README.md
since it seems to be a requirement right now
=> add venv instructions to readme

docs/central-entities.rst, docs/img/central-entities/entity-detail.png, docs/img/central-entities/entity-edit.png, docs/img/central-entities/entity-landing.png, docs/img/central-entities/entity-settings.png, docs/img/central-entities/entity-table.png
should be complete but because i can't get this dev env to work i haven't actually compiled this. i'll try again tomorrow if i have time or someone else can take this the last mile.
=> central: docs for entity table, detail, edit, settings.

docs/incl/form-examples/regex-middle-initial.rst
closes #1477 
Just fixed the regex from https://docs.getodk.org/form-logic/#id31
=> Fixed regex

docs/form-operators-functions.rst
closes #1222
I've added examples for every option:
=> Clarify that area and distance functions work with concatenated points or nodesets of points

docs/central-entities.rst
PR at https://github.com/getodk/docs/pull/1621 didn't deploy for some reason.
=> Edits and API deletes are available, so we are out of preview

docs/collect-install.rst, docs/form-question-types.rst
closes #1639
I've added a description to deviceid.
=> Update deviceid description

docs/collect-filling-forms.rst, docs/img/collect-filling-forms/question-screen-highlight-check-for-errors.png, docs/spelling_wordlist.txt
closes #1631 
I've described how to validate forms during form entry.
=> Describe check for errors during form entry

docs/central-install-digital-ocean.rst
Closes https://github.com/getodk/central/issues/420.
=> SMTP auth is required

docs/collect-shortcut.rst
closes #1283 
I've added a warning:
=> Document how form shortcuts work with form versions

docs/_static/api-spec/central.yaml
Copied API docs from central backend
=> updated API doc for v2023.4 Central release

docs/xlsform.rst
=> Add entities sheet

docs/central-install-digital-ocean.rst
This PR is in response to these issues...
* Provide hint about sender addresses
https://forum.getodk.org/t/central-new-install-unable-to-login-after-shifting-to-custom-email-server/43439/4
* Make sure Central uses the swap you allocate
https://forum.getodk.org/t/build-frontend-sh-returning-npm-err-timeout/43120/10
=> More hints to guide self-hosters

extensions/openapi/__init__.py
=> Disable escaping in mustashe

docs/index.rst
I think of this as Install, Use, then Manage.
=> Use before manage

docs/central-install-digital-ocean.rst
=> Match style

docs/collect-forms.rst, docs/img/collect-forms/drafts-action-menu.png, docs/img/collect-forms/drafts-bulk-finalized.png
Closes https://github.com/getodk/docs/issues/1673
=> Document bulk finalization

docs/collect-filling-forms.rst, docs/img/collect-filling-forms/rename-form.gif, docs/img/collect-filling-forms/rename-form.png
Fixes some weirdness I noticed after the latest changes.
=> Improve language changing section

docs/form-datasets.rst, docs/spelling_wordlist.txt
Closes https://github.com/getodk/docs/issues/1330
I decided to only document `xml-external` in a note because it's unlikely to be common.
=> Document csv-external

docs/conf.py
=> Try page.html

docs/_static/css/custom.css, docs/_templates/page.html
@alyblenkin helped me get a reasonable first pass for styling, we'll come back for more polish.
=> Add rating feature to page footer

docs/form-question-types.rst, docs/spelling_wordlist.txt
closes #1652
It documents using custom camera apps in Collect
=> Document using custom camera apps in Collect

docs/collect-import-export.rst, docs/collect-settings.rst
closes #1753
I've updated basemap settings as one of the options has been removed.
=> Updated basemap settings

docs/form-question-types.rst
closes #1693
I've added a warning to describe the problems that using this type of question might cause.
=> Improved the description of the string widget with numbers appearance

docs/guide-form-language.rst
=> Use correct image

docs/conf.py, docs/robots.txt, requirements.txt
Sitemaps help with SEO. This seems to be the de-facto plugin.
I don't love that it includes orphan pages by default, but maybe we can find someway to post-process the sitemap.xml
=> Add sitemap

docs/img/tutorial-community-reporting/address-problem.png, docs/tutorial-community-reporting.rst
=> Fix current expression to account for JR bug

docs/central-users.rst, docs/collect-connect.rst, docs/collect-import-export.rst, docs/img/central-users/app-users-code.png, docs/img/central-users/app-users-create.png, docs/img/central-users/app-users-created.png
=> Add details about settings QR codes

docs/collect-settings.rst, docs/xlsform.rst
closes #837 
This documents how to use auto_send and auto_delete on a form level.
=> Document auto_send and auto_delete

docs/_static/api-spec/central.yaml
This PR copies the latest version of docs/api.yaml from the central-backend repo in preparation for the release of Central v2024.1.
=> Update API docs for v2024.1

docs/central-entities.rst
=> More performance

docs/_static/api-spec/central.yaml
=> Update Central API docs to fix some 403 issues

.circleci/config.yml, docs/conf.py
Found these with an ahrefs site audit
=> Sitemap excludes

docs/entities-intro.rst
Given that this page is a top link in the nav bar, I think it'd be nice to have a quick video. People like videos!
=> Add video and text from central-entities

docs/entities-intro.rst
=> Add image and separate out video

docs/form-question-types.rst
In response to https://forum.getodk.org/t/documentation-on-odk-geopoint-format-discrepancies/47547
=> Fix selected-at indexing

docs/entities-intro.rst, docs/img/entities-intro/multiple-entity-list-attachments.png
Clarify that multiple Entity Lists can be attached to a form, clarify details around how to use select one and csv-external.
=> Add details about attaching Entity Lists

docs/form-question-types.rst
closes #1823 
Instead of adding a note (as mentioned in the issue), I've added a separate point for every type of choice (point, line, polygon). I think it makes more sense than a note but if you don't agree please let me know.
=> Make it clear which properties can by used with which types of choices

docs/entities-intro.rst
I'm explicitly not updating the video at https://docs.getodk.org/central-entities/#introducing-entities because I think that video has accompanying forms that are useful.
=> Better demo video

docs/collect-offline-maps.rst, docs/form-language.rst, docs/form-question-types.rst
Putting the video in see also looks and feels better to me.
=> Replace link with geo features overview

docs/central-install-digital-ocean.rst, docs/central-intro.rst, docs/collect-intro.rst, docs/conf.py
I will review this with the user who thought self-hosting was a must and confirm this language works.
I've put this on the high-traffic landing pages where we don't really mention ODK Cloud.
=> Remind users that self-hosting is not required

docs/_static/api-spec/central.yaml
This PR updates the Central API docs immediately before the release of Central v2024.2.
=> Update Central API docs for v2024.2

docs/central-entities.rst
I think most people will be looking for something that says importing/uploading CSVs.
=> Better title

docs/central-install-digital-ocean.rst
* Renamed memory allocation to RAM allocation because it's more likely to be what people are looking for.
* Moved Upstream SSL and DKIM to bottom because they aren't really tested or common
* Moved S3 storage to custom database
* Removed additional DigitalOcean storage because people should just resize the entire machine or use S3
=> Re-order for relevance

docs/security.rst
=> Improved DDoS language

docs/form-logic.rst
closes #1853 
This pull request only improves the description of how to define repeat instance label.
=> Improve description of how to define repeat instance label

docs/entities-intro.rst
There wasn't really enough there to get quickly started!
=> Add details on updating Entities

docs/collect-troubleshooting.rst, docs/form-datasets.rst
Closes https://github.com/getodk/docs/issues/1897
Once I add the section on preventing duplicates using Entities, I'll link it from here.
=> Add troubleshooting instructions for repeated xpath error

docs/_static/api-spec/central.yaml
This PR updates the Central API docs immediately before the release of Central v2024.2.
=> Update Central API docs for v2024.3

docs/central-install-digital-ocean.rst, docs/central-upgrade.rst
Got most of the language from https://github.com/getodk/docs/commit/8189771d9e680d26a97d7e50568ba0765f4bd0b5. I tried to remove all the extra words.
=> Re-add firewall requirement

docs/downloads/security/ODK-Pentest-2024.pdf, docs/security.rst
Merge https://github.com/getodk/website/pull/682 after merging this.
=> Add pen test

docs/security.rst
Make sure file gets copied on build
=> Fix download link

docs/form-question-types.rst
@latin-panda I've added some more detail to the random seed description that will hopefully be helpful. Let me know what you think and if you have ideas for more information that would be helpful for end users.
=> Add details about random seeds

docs/entities-intro.rst
Add more details about performance with large Entity Lists.
=> Revise section about millions of Entities

docs/entities-intro.rst, docs/entities-reference.rst, docs/entity-cheat-sheet.rst, docs/entity-form-reference.rst, docs/index.rst, setup.py
This is meant to be a short page with all the guidance about what to put in your entity forms all in one place. This is located under Form Design > Entities Reference.
I also wanted to highlight two comments in the forum that were useful and have been formalized in these docs:
1. https://forum.getodk.org/t/referencing-dataset-label-from-select-one-as-text-in-next-question/39467/5
2. https://forum.getodk.org/t/updating-and-creating-entities-with-one-follow-up-form/45385/6
=> Quick reference for working with entities in forms

docs/central-install-digital-ocean.rst
Closes https://github.com/getodk/central-backend/issues/1452
=> Update permissions for minio v8

docs/form-question-types.rst
Closes https://github.com/getodk/docs/issues/1870
=> Add background-geopoint

docs/central-upgrade.rst
We could maybe mention Sentry tracing but I don't think we need to. @alxndrsn? There will be info on that at https://github.com/getodk/docs/pull/1933
=> Central v2025.1 has no special upgrade notes

docs/form-question-types.rst
Closes https://github.com/getodk/docs/issues/1969
=> Specify PDF147 encoding

docs/form-question-types.rst, docs/spelling_wordlist.txt
Closes https://github.com/getodk/docs/issues/1936
=> Multiline text

docs/collect-external-apps.rst
Closes https://github.com/getodk/docs/issues/1942
=> Groups that are not field lists can launch apps

docs/collect-forms.rst
As requested by @yanokwa in https://github.com/getodk/docs/pull/1971#pullrequestreview-2984609460
=> Improve formatting
