circle.yml

Closes #64 
I verified this works by SSHing into the build machine and running the various commands.
The risk I see with merging this PR is that pngquant is by default not verbose, so if the compression takes longer than 10 minutes with no output, CirceCI will terminate the build. 
We can fix this by adding -v to the png command or increasing the timeouts on the command, but I'd like to see how this PR behaves first.

Optimize PNGS images

---

circle.yml

I assumed that the existing circle.yml file overwrites the source images. It doesn't, and this command implements the behavior I wanted.

Overwrite source images when publishing

---

b.sh
circle.yml

Closes #80 
The `-W` flag turns warnings into errors. I've confirmed this shows an error by temporarily breaking an image link.

Warnings as errors

---

circle.yml

png compression now takes 3 minutes which is less than the 10 minute limit that CircleCI uses to kill apps, so we don't need constant output.

Silence pngquant

---

collect-install.rst

Very small change. Just displayed the links properly in `.rst` format.

Displayed hyperlinks properly (line edit)

---

contributing.rst

Above screenshot reflects the changes.
Closes https://github.com/opendatakit/docs/issues/75

Adds information about compressing images. 

---

contributing.rst

Another minor fix.
Replaced `:abbr::` with `:abbr:`

Line Edit - corrected UI label in document

---

contributing.rst

This is with reference to Issue No. #96
These are a bunch of quick fixes to minor issues I found while reading contributions.rst. I figured that this was as good a place to start as any. 
Proposals: I would like to add a line talking about the variant of English used throughout the docs. I would also like to add some missing points in the "submit a PR" section wrt getting changes from upstream.

Line edits for contributing.rst 

---

contributing.rst

I've added information about how one can add videos to the docs.
Please find the attached screenshot. 
Closes https://github.com/opendatakit/docs/issues/148.

Information about "How to include video in docs" added.

---

cygwin.rst
index.rst

I added instructions on setting up odk docs environment for windows using cygwin. I created (cygwin.rst) document and add a reference to the document in the index file under "Contributing to ODK Docs".
There is some repetition of steps in windows installation similar to linux; however, there are also some differences. It is possible also to integrate windows docs installation into the current (contributing.rst). We may add notes for windows under each step in the main contributing doc.
This is an issue #95

 Installation steps of Docs in cygwin

---

collect-adb.rst
index.rst

Added a new document for using `adb` with Collect. Currently addresses following things:
* What is Android Debug Bridge (adb)?
* Downloading adb
* Using adb with Collect
Still doesn't include possible errors one can face.
Needs more exploring.
Still not referenced anywhere in `collect-forms.rst`

Added a separate document for adb

---

collect-forms.rst
contributing.rst

Added the custom text roles section to sphinx-specific markup.
closes #113 
closes #108

Documented the text roles

---

_static/css/custom.css

Menuselection has been styled similar to guilabel. The border of the box has been made black which makes it similar to guilabel but not same.
Addresses https://github.com/opendatakit/docs/issues/109.

Menuselection styling added

---

collect-adb.rst
contributing.rst

This PR adds the following changes:
* It changed the default console type commands to use `none` as code-block type.
* Some of the restructured text examples used `rest`, changed all of them to `rst`, which is in accordance with the guide itself.
* Added a note for the use of `none`.

Changes the code-block type for terminal commands

---

contributing.rst

Added the rule that we'll observe in our writing about the usage of `guilabel` and `menuselection`.
Closes #109

Documented the rule that we'll observe in our writing

---

briefcase-forms.rst
collect-forms.rst
form-widgets.rst

Added section labels in briefcase-forms.rst.
This pull request addresses #96.

Added section labels and fixed some typos

---

circle.yml

Bad pngs can cause pngquant to fail before a build goes to production (See https://github.com/opendatakit/docs/issues/323). We should catch this issue when the initial PR is sent in. For this reason, we should run pngquant as part of the test. This makes for slower builds when a PR is sent in, but so be it. I'd rather we catch this before we merge.
We only need to use s3_website when deploying to production, so rather than install it on each commit, we only install it when deploying to production.

Move pngquant as part of test. Move s3_website as part of deploy.

---

requirements.txt
ss.py

closes #330 
I've added a function that checks and converts the color profile of bad pngs. 
I've added a temp.py for testing purposes and jumpscreen.png(a bad png) in img/collect-settings. The script can be tested on this bad png(it successfully converts the color profile) and on any other png.
I'll remove the files once the script has been finalized, however it's ready for review now.

Added script to convert the color profile

---

index.rst
openrosa.rst

closes #332
- Moves JavaRosa and OpenRosa under "Developing with ODK"
- Puts OpenRosa APIs TOC on the OpenRosa page. (BTW -- I think this solution would help with #105)
I'd like to re-order the sidebar TOCs

Moves dev-focused docs to own section

---

contributing.rst
projecting-collect.rst

Added information on using the command line to run the emulator and removed outdated information as standalone SDK no longer includes adb.

Added information on using command line to run the emulator 

---

aggregate-install.rst

addresses opendatakit/opendatakit#1360
The current AMI version is: Amazon Linux AMI 2017.09.1 (HVM), SSD Volume Type - ami-32d8124a and no longer includes the tomcat6 package currently referenced in the docs.
Also fixes where the command for **Install MySQL** was noted as `sudo yum install tomcat6` and not `sudo yum install mysql mysql-server`.

reference tomcat 8 (not 6) in aws install

---

form-design-intro.rst
index.rst

addresses #239 
addresses #332
A new doc at the top of the Form Building TOC that provides an overview of how forms work in ODK ecosystem. 
This is roughly analogous to https://opendatakit.org/help/form-design/
The [original page](https://opendatakit.org/help/form-design/) has a number of sub pages, only some of which will be pulled in.
I'm also going to move some pages around and do some editing, but since this doc is useful immediately, I thought it was more sensible to do a standalone PR for it.

Form design intro

---

_static/js/custom.js

This is a *hot fix* for a bug I discovered while testing a PR with a lot of details blocks.
The details blocks relied on a random-generated id. However, this was prone to collisions. This caused some panels to simply not open when toggled.
The solution here is to use a simple incrementing id. This has the added benefit of running faster.

replaces random id with incremented id

---

form-widgets.rst

closes #296 
Changed media location in form-widgets.rst to a folder labeled ``form-name-media``

Fixed location of media in form-widgets.rst

---

.circleci/config.yml

Fixes broken build. 
I tested this by SSHing into the failed machine and confirming that `openjdk-7-jre-headless` was no longer available in the `circleci/ruby:latest` docker image.
I then tried `openjdk-8-jre-headless` which installed, and then I successfully ran the follow on commands:
* `gem install s3_website && s3_website install`
* `s3_website push`

Java 7 is no longer supported in CI image

---

contributing.rst
s3_website.yml

Fixes #425 
Fixes #426 
Fixes #414
In [my research](https://stackoverflow.com/a/15133106/152938), I have learned that URL fragments (the stuff after the hash/bang) does not get sent to the server. Because of this, S3 (and probably any other service that would rewrite URLs) cannot redirect based on the hash. 
You could do the [redirect with JavaScript](https://stackoverflow.com/a/24377443/152938), but that feels hacky.
I confirmed the above by testing all the various combinations of urls (e.g., `collect-install/#connecting-to-a-server`, `collect-install#connecting-to-a-server`) to see if I could get a redirect working. I could not.
I verified this change by testing on my own S3-based static website and confirming that the url/index.html syntax redirect when I type `url`, `url/`, …

Remove hash redirects because they are not supported on S3

---

.circleci/config.yml

This isn't technically an issue on docs, but for consistency with the rest of the tools is nice to have.

Use work instead of src to reduce confusion when SSHing into CircleCI

---

aggregate-admin.rst
aggregate-best-practices.rst
aggregate-data-access.rst
aggregate-forms.rst
aggregate-setup.rst
aggregate-tomcat.rst
aggregate-use.rst
index.rst

closes #440
addresses #398 
- Moved the TOCs around a little to better match what we did with collect
- Updated titles to used gerund verbs wherever appropriate
- added a mention of the MySQL table row width problem
It might be worthwhile to expand the section I added about choosing a database into a larger document about pros/cons etc. of different RDBMSes. But... it might not be. The information I wrote there covered the problem identified in #440, but it doesn't really mention any other concerns.
I don't like any solution to the question of consistent titling. I prefer gerunds for a lot of reasons, and that's what we've settled on for this repo. But then sometimes they seem like the weirdest possible way to write a title (like `Administering Aggregate` rather than `Aggregate Admin`, …

Aggregate fixes

---

_static/js/custom.js

closes #448
If a details block only contains a screenshot, the show/hide label says "Screenshot" instead of "Details"
Now that so many labels on some pages say "show screenshot," it isn't clear why the other screenshots are displayed by default. This will take some thought as I work through editing for style.

fixes show details labels

---

style-test.py

closes #473 
Output option is used instead of output argument with type as path. So, any path will be treated as ``out_path`` only when ``-o`` flag is specified.

Change output argument to an option

---

requirements.txt
style-test.py

closes #477 
Added option ``-d`` to run checks on currently modified files based on ``git diff``.

Add option to run tests on currently modified files

---

style-test.py

closes #470 
``gen_list`` function is added which can be called from another python script to return a list of errors and warnings.

Added function to return error list

---

style-test.py

addresses #471 
closes #476 
closes #478 
- Ignore blank lines in directive blocks. Instead of ``\n`` check, ``isspace()`` check is used to ignore any lines with leading whitespace as well.
- rst directive blocks are already ignored. Check to ignore comments is added.
- Function to replace quote marks.

Improved check for ignoring directive blocks, comments and quotes

---

.circleci/config.yml
style-test.py

closes #493 
Style testing is only performed on changed files by using command ``git diff origin/master... --name-only`` to generate changed file list.

Enables testing only on changed files

---

style-test.py

closes #499 
Search path for style-test script is fixed to check for ``.rst`` files in the ``src`` directory.

Fix search path for style guide testing

---

src/docs-developer-guide.rst

addresses # 96
Simple line edit to correct three instances of a capitalization mistake in documentation: css to CSS.
I am not a computer scientist and am still learning to use GitHub and Git Bash on Windows.  I attempted to make this line edit using the command line but ran into some errors that I am still trying to sort out for future contributions.  For now I have used GitDesktop to submit my contribution, but I know this is not canonical and that I will need to learn to use Git Bash effectively.  I am locating online resources to help me address the command line difficulties I am having so that I may do this the standard way in the future.  (I also realize that I need to learn more about the system ODK uses for attaching a PR to an open issue.  My apologies for not know what …

Line edit documentation

---

requirements.txt
src/aggregate-intro.rst
src/conf.py

closes #513 
- `conf.py` is edited to make explicit the smartquotes option
The transform is left ON for dashes and ellipses, but turned off for quotes
- `requirements.txt` is updated, as the smartquotes options require later versions of Sphinx and docutils
I would have preferred to only disable smartquotes within specific directives, 
as it is better to leave them on for normal prose.
But this would have required custom coding, I think,
as such an option does not currently exist.
(If this option is added in the future, we may want to consider it.)
The ability to specify options for the smartquotes parser was new in Sphinx 1.6.6,
prior to this PR, we are on 1.6.1
I *tried* updating to Sphinx 1.7, but this broke the custom directives.
If there is a reason in the future to upgrade past …

removes curly quote transform

---

.circleci/config.yml
s3_website.yml
src/_templates/footer.html
src/collect-filling-forms.rst
src/conf.py
src/img/collect-completing-forms/long-press-to-remove.png
src/img/collect-completing-forms/multi-select.png
src/img/collect-completing-forms/rename-form.png
util/resize.py

closes #271 
- Added pdf output generation
- Changed image ordering for html builder to choose gif over png
- Added png images as substitutes for gif for latex builder
- Script to resize images
- Large tables are not rendered properly
- There are still some underfull and overfull issues.
- We need to run xelatex engine twice
EDIT: The first commit needs to be dropped once #536 is merged!

PDF output

---

.circleci/config.yml

closes #561 
PDF is copied over to build directory after generation so that the file is available for download. I have tested this locally and it works fine!

Fix pdf download

---

.circleci/config.yml
src/_templates/footer.html
src/conf.py

This combines a few things.
* Renames the pdf to something a bit more sensible (ODK Documentation)
* Moves the PDF to downloads
* And persists the workspace so the deploy can find it. 
I'm not 100% sure the last bullet works, but there's only one way to try it.

Fix PDF links

---

Makefile

closes https://github.com/opendatakit/docs/issues/578
Updates Makefile with new soft clean task that will leave the odkX-build directory intact when running `make odkX`. This is useful so that you can leave your python server running and not need to restart it each time you recompile.

Add soft clean to leave build folder intact for python server

---

.circleci/config.yml
odk1-config/s3_website.yml
odk2-config/s3_website.yml
shared-config/s3_website.yml

1. This PR adds `s3_website.yml` configuration for odk2-docs and shared-docs. Given that there will be 3 `s3_website.yml`, the 3 files are placed in their respective `*-config` directory. 
2. `objects.inv` is removed from `s3_website.yml` exclude list. This file is essential for [intersphinx](http://www.sphinx-doc.org/en/master/ext/intersphinx.html).
3. CircleCI `deploy` job is split into 3: `deploy-odk1`, `deploy-odk2`, and `deploy-shared` to support separate deployment for these 3 Sphinx sites that will act as 1 website using AWS CloudFront. At this point there is no need to deploy shared, however by setting this up it will allow the cross referenced files to be added back into our documentation instead of having duplicate files copied into each deployment.

Multi-bucket Deployment

---

odk1-src/conf.py
odk2-src/conf.py
shared-src/_templates/footer.html

1. Add intersphinx mappings to `odk1-docs` and `odk2-docs`. This will enable cross linking between documentations.
2. Use `pathto` to generate proper relative links for PDF download and Contributor's guide
**note**
In the build log, there will be warnings about missing `objects.inv` for odk1-docs and shared-docs. This is expected, as odk1-docs is still served by the old S3 bucket (prior to the conversion to multi-bucket setup) and shared-docs is empty now.

Add intersphinx mapping

---

odk1-src/collect-filling-forms.rst
odk1-src/collect-forms.rst
odk1-src/collect-offline-maps.rst
odk1-src/collect-settings.rst
odk1-src/form-widgets.rst
odk1-src/img/form-widgets/coptic-calendar-widget.png
odk1-src/img/form-widgets/ethiopian-calendar-widget.png
odk1-src/img/form-widgets/image-map-choose-shape-0.png
odk1-src/img/form-widgets/image-map-choose-shape-1.png
odk1-src/img/form-widgets/image-map-choose-shapes-0.png
odk1-src/img/form-widgets/image-map-choose-shapes-1.png
odk1-src/img/form-widgets/integer-thousands-sep-widget-spaces.png
odk1-src/img/form-widgets/integer-thousands-sep-widget.png
odk1-src/img/form-widgets/islamic-calendar-widget.png
odk1-src/img/form-widgets/new-image-widget.png
odk1-src/img/form-widgets/range-decimal-default-widget.png
odk1-src/img/form-widgets/range-decimal-vertical-widget.png
odk1-src/img/form-widgets/range-integer-default-widget.png
odk1-src/img/form-widgets/range-integer-vertical-widget.png
odk1-src/img/form-widgets/range-widget-picker-0.png
odk1-src/img/form-widgets/range-widget-picker-1.png
odk1-src/img/printer-widget/printed-labels.png
odk1-src/printer-widget.rst
shared-src/spelling_wordlist.txt

closes #566 
closes #569 
closes #38 
closes #411 
closes #378 
closes #570 
closes #568 
closes #490 
Near-complete rewrite of `form-widgets.rst`, including new sections for several additional widgets.
Few things (misspellings, etc.) that I think should have been caught by style checks, but weren't. Will file a few issues against this.
(Before I forget: labelled/labeled, XSLForm)
Shrink images a bit more.

Restructure form widgets

---

odk2-src/aggregate-tables-extension.rst
odk2-src/getting-started-2.rst
odk2-src/select-tool-suite.rst
shared-src/docs-style-guide.rst
shared-src/docs-syntax-guide.rst
shared-src/faq.rst

addresses https://github.com/opendatakit/docs/pull/480#issuecomment-372384246
Adds back relative references that were removed when the source directory was split into ODK 1, ODK 2, and shared source.

Add back references across sites

---

odk1-src/_static/css/custom.css
odk1-src/form-widgets.rst
odk1-src/img/form-widgets/area-calc-0.png
odk1-src/img/form-widgets/area-calc-1.png
odk1-src/img/form-widgets/area-calc-2.png
odk1-src/img/form-widgets/area-calc-3.png

closes #23 
Info on using `area()` to get area of a geoshape.
Also:
some CSS to make it so you can use line breaks in a csv-table
Brought up on Slack ---
I had some issues with geotrace map on a device with no cell connection.
Using Google Maps, the widget opened to a white screen with no map displayed.
Using Open Street Maps, it kept resetting to 0,0.
I wanted to test if `area` worked on a geotrace-defined polygon (I assume so), 
but I was unable to test geotrace because of this issue.
I just included the info in geoshape. IT might be good to add a note to geotrace if it works there as well.

adds info on area calculation

---

odk1-src/conf.py
odk2-src/conf.py

`shared` is not a sphinx site --- it gets pulled into odk1 and odk2 at build time
so we shouldn't include it as an intersphinx mapping
Additionally, I commented out the python mapping,
as I don't see (currently) as reason for us to be referring to it.

remove shared and py from intersphinx

---

odk1-src/form-widgets.rst

closes #283 
A note in form-widgets (Question Types) about the effect of time zone and DST.
I don't really have a suggested workaround for this problem.

adds note about time zone issue for time widget

---

odk1-config/s3_website.yml

Addresses #630
Since we removed form-interaction, we should redirect it to form-logic (which is some fantastic content, BTW). I think this is how we do redirects now.
I think @adammichaelwood has a magical script that was supposed to prevent this mistake from happening. Maybe. It'd be good to know where the knowledge gap is.

Redirect form-interaction to form-logic

---

odk1-src/form-repeats.rst

closes #661 
removes the section about referencing responses from previous repeat iterations
If we think of a good use case for why someone would want to reference a previous iteration,
(other than populating a default, which is what most people want to do, but can't)
we would want to add this section back.
Shame on me. Shame on my family. Shame on my cow.

removes section on referencing previous iterations

---

odk1-src/_static/css/custom.css
odk1-src/conf.py
odk1-src/form-functions.rst
odk1-src/form-logic.rst
odk1-src/form-operators-functions.rst
odk1-src/form-repeats.rst
odk1-src/img/form-functions/choice-name-multi-lang-english-0.png
odk1-src/img/form-functions/choice-name-multi-lang-english-1.png
odk1-src/img/form-functions/choice-name-multi-lang-spanish-0.png
odk1-src/img/form-functions/choice-name-multi-lang-spanish-1.png
odk1-src/img/form-functions/count-selected-constraint.png
odk1-src/img/form-functions/selected-at-0.png
odk1-src/img/form-functions/selected-at-1.png
odk1-src/incl/form-examples/constraint-on-selected.rst
odk1-src/incl/form-examples/parallel-repeat-groups.rst
odk1-src/incl/form-examples/regex-middle-initial.rst
odk1-src/incl/form-examples/sum-to-count-responses.rst
odk1-src/index.rst
video.py

- Function and operator reference
- Reusable form examples pulled into includes
- conf.py updated to use JS domain by default (See below)
- custom css to make function reference easier to read
- fixed a few form examples (form-logic and form-repeats) that were either wrong or had typos
Opening an ongoing issue to add useful examples.
A few of the functions listed in the XForm spec weren't clear, and a few weren't relevant --- tracking that down was a minor pain.
cf: https://opendatakit.github.io/xforms-spec/#xpath-functions
In Sphinx, function references like this are done using language specific domains.
cf: http://www.sphinx-doc.org/en/master/usage/restructuredtext/domains.html
There is no XForm/XPath domain. I tried using the default domain (Python), but the syntax didn't work out. …

Form functions

---

odk1-src/form-styling.rst

closes #699 
- mention of inline html, with lots of caveats
- link to list of supported tags
- mention that span/style only supports color and font-family
- remove the html xlsform sample for header size comparison
(left the image, because I think it is useful)

adds inline html

---

odk1-src/form-question-types.rst
odk1-src/img/form-question-types/file-upload-open-from.png
odk1-src/img/form-question-types/file-upload-widget.png

closes #667 
A new widget section for the file widget.
[This conversation about Pyxform support](https://github.com/XLSForm/pyxform/issues/194) and the [PR that satisfies it](https://github.com/XLSForm/pyxform/pull/198) suggests that a form designer could specify allowed file types, but I can't find an example of how it would be done. The PR includes a sample XLSX file, but it doesn't specify any file types.
This PR should not be pushed until the associated Collect and Pyxform features are released.

adds file widget

---

odk1-src/form-styling.rst

addresses #96 
Fixes a broken ref in form-styling.rst
This broken ref should never have made it into `master`,
as it should have been caught in testing.
The problem seems to be that we are no longer raising Warnings as Errors.
(Adding issue for this.)

fixes broken ref

---

.circleci/config.yml
Makefile

closes #721 
Adds two new make commands:
`make odk1-deploy`
`make odk2-deploy`
These are the same as the `odk*` versions, but with the addition of the `-W` flag,
to raise Warnings as Errors.
Then, `.circleci/config.yml` is updated to use the `-deploy` versions.
Until #720 is merged, this branch contains a broken ref, which should now trigger a build error.

adds -W to make

---

odk1-src/form-question-types.rst
shared-src/spelling_wordlist.txt

closes #667 
- Warning on file upload widget.
- Added "antimalware"  and "antivirus" to spelling list. (I only used "antimalware" in the new text, actually).
in re:
- antimalware instead of antivirus
- antimalware instead of anti-malware
cf: https://docs.microsoft.com/en-us/style-guide/a-z-word-list-term-collections/a/antimalware

adds warning to file upload widget

---

odk1-src/form-question-types.rst
odk1-src/img/form-question-types/self-portrait-0.png
odk1-src/img/form-question-types/self-portrait-1.png
odk1-src/img/form-question-types/self-portrait-2.png
odk1-src/img/form-widgets/selfie-complete.png
odk1-src/img/form-widgets/selfie-in-progress.png
odk1-src/img/form-widgets/selfie-start.png

closes #723 
Updates the selfie widget section to use the new-front appearance.
This PR should not be merged until v.1.15 is released.

change selfie to new front

---

odk1-src/form-logic.rst
odk1-src/form-operators-functions.rst
shared-src/spelling_wordlist.txt

closes #731 
- add a "gotcha" subsection to Form Logic building blocks
- demote "when expressions are evaluated" to subsection of gotcha
- add section on nil values to form logic gotchas
- fix some incorrect section header underlining in that file
- add NaN to spelling list
There's no obviously good place to put this info. @lognaturel suggested a warning in the math operators section, but it applies to math functions and potentially comparisons as well. 
What I came up with makes sense to me, but if anyone disagrees I am open to other ideas.

Adds section about empty number values

---

odk2-src/services-install.rst

previous link goes to a partially broken page with no apparent way to download
not sure if link should be updated to http://opendatakit.org/software/odk2/ (currently in this PR) or straight to https://github.com/opendatakit/services/releases (which you end up clicking through to from the former link) or something else?

link update

---

odk1-src/form-question-types.rst

It's not immediately obvious that the picker can be tapped to change the value in discrete increments of 1. This can be very useful when counting things as described in https://forum.opendatakit.org/t/dark-theme-radio-buttons-hard-to-see/13499/9?u=ln

Clarify that the picker can be dragged or tapped

---

odk1-src/collect-sms-submissions.rst

addresses #782
Modification to documentation to use ``compact_tag`` instead of ``short_tag`` for ODK Collect to properly send data fields over SMS.

Modify use of short_tag to compact_tag per current pyxforms

---

odk2-src/aggregate-tables-extension.rst

Support for google accounts was removed from ODK Services, therefore, the documentation should only talk about Aggregate usernames.

drop google accounts from docs

---

odk1-src/form-question-types.rst
odk1-src/img/form-widgets/rank-blank.png
odk1-src/img/form-widgets/rank-drag.png
odk1-src/img/form-widgets/rank-ordered.png

Closes #747 
Describes the rank widget usage, shows its XLSForm usage and adds 3 screenshots of a rank question with a blank value, an active ranking and a rank question with a set value.
Verified by running locally, clicking on all links introduced and running `make odk1-check`.

Describe rank widget

---

shared-src/docs-style-guide.rst

Related issue: https://github.com/opendatakit/docs/issues/261
closes #
addresses #

Removed link to /use which is redirected to docs

---

shared-src/docs-tech-guide.rst

addresses #96 
Typos and grammar.

Typo and grammar fixes

---

odk1-src/aggregate-upgrade.rst
odk1-src/collect-install.rst
odk1-src/security-privacy.rst
shared-src/docs-style-guide.rst
shared-src/faq.rst

* Release notes are now split between old versions and new versions
* These are user docs, so reference the most likely use of an emulator
* Our source is on GitHub. We can say that more directly
* XLSForm link is local. Also, Gumroad isn't a thing we use anymore
* The developer wiki is out of date and not that useful

Update links that are no longer relevant

---

odk1-src/launch-apps-from-collect.rst

closes #775 
Adds `uri_data` docs and examples.
I also added some more detail on how this appearance relates to intents because I think it's hard to generalize usage without that context.
I removed the XML output for the simple case but left it for the `field-list` case because it's not currently documented anywhere else.

Document special uri_data parameter used to specify intent data when launching external app

---

odk1-src/aggregate-deployment-planning.rst
odk1-src/aggregate-field-length.rst
odk1-src/form-best-practices.rst
odk1-src/form-question-types.rst

closes #745
addresses #
Description of why there's a 255 char limit on Aggregate db text fields. Instructions on increasing that value on specific questions in XLSForm. Warnings in places users are likely to hit this limitation.

Describe how to increase Aggregate db field length beyond 255

---

odk1-src/form-language.rst
odk1-src/form-styling.rst
odk1-src/img/form-styling/media-image.png
shared-src/spelling_wordlist.txt

looks to resolve #749
- Adds some more detail to the form-language section to try and avoid issues when using a media column in a multi-lingual form.
- Adds a section on media to form-styling per suggestion from @adammichaelwood in issue thread.
- I didn't see any flags from the spelling and style checks that were a result of my edits.
- Get feedback on if wording changes/additions help clarify or just reduce brevity without helping improve docs.
- Get feedback if adding a media section to form-styling is the right move.
- I had trouble getting the `style-test.py` to run on just the diff or a specified file. I could get `python style-test.py -r odk1-src` to run on all the docs but didn't figure out the additional parameters.
- Took me a second to realize that `sphinx-build -b spelling src …

media in question prompt clarifications

---

odk1-src/img/form-styling/media-image.png

Addresses #836 
Ran the image through ImageOptim to shrink it. It's still much larger than most of our other images, but I think that's due to the fact that it has a hard to compress section (e.g., the coffee cup)

Lossless image compression of media-image.png

---

odk1-src/aggregate-admin.rst
odk1-src/aggregate-boost-performance.rst
odk1-src/aggregate-limitations.rst
odk1-src/aggregate-upgrade.rst
odk1-src/openrosa-form-submission.rst
odk2-src/odk-2-sync-protocol.rst

Minor copy edit to fix AppEngine when used in text. See https://cloud.google.com/appengine for proof that the spelling requires a space.

Google writes App Engine with space

---

odk1-src/collect-sms-submissions.rst

I think this corrects the example of an SMS form submission with custom delimiter.  The text implies that fields should be delimited by `+`, but the example shows a `|` (pipe).  Pipe wouldn't be a great delimiter to pick, as it's not included in the [standard GSM SMS character set](https://en.wikipedia.org/wiki/GSM_03.38#GSM_7-bit_default_alphabet_and_extension_table_of_3GPP_TS_23.038_/_GSM_03.38).

Correct sms submission custom delimiter example

---

odk1-src/collect-sms-submissions.rst

@alxndrsn's #875 made me realize there were other issues with the SMS documentation. This PR escapes characters as needed, fixes spacing to get paragraph breaks in the expected places and improves some wording.

Fix wording and escape characters in SMS docs

---

shared-src/docs-tech-guide.rst

Also fixes a few nearby grammar errors.
Closes #881.
This updates the recommended command to run the spelling checker.
None.
Nothing.
The spelling checker does not run at all with the current command.  The new command runs the spelling checker, though it generates a lot of complaints about misspelled words.  The next step is to add the list of all the misspelled words to the `spelling_wordlist.txt` file as recommended by https://docs.opendatakit.org/docs-tech-guide/.

Update the command to run the spelling checker.

---

odk1-src/security-privacy.rst

Closes #832 
Update to current practice and re-arranging so it's easier to read. The big changes are 
* Combining all the Aggregate things in one section and moving the bits that are focused on encryption into the general encryption section so it's easier to read.
* Dropped the Google Account section because it's no longer relevant for Aggregate.
* Update the rest of the tools language to match current practice
* Creating a new cross-tool concerns section
I think the easiest way to parse these changes is to read the docs at https://docs.opendatakit.org/security-privacy and compare it to what this PR has.

Update security privacy

---

odk1-src/getting-started.rst

closes # not applicable
Drops down the "A" in App under **Install Collect** "The easiest way to install the Collect App is to get it from the Google Play store."
No known associated issues as a result of this PR.
This issue is resolved.
No problems encountered.

Change App to app

---

odk1-src/form-operators-functions.rst

see the discussion at:
https://forum.opendatakit.org/t/value-produced-by-decimal-date-time/15751
should this edit add the additional detail about "it's the format used by Excel but off by 70 years" instead of just removing the sentence?

remove misleading note

---

odk1-src/aggregate-admin.rst

Closes #887
Removed very specific text and replace with more generic warning.  Put said warning in a warning block. Clean up some blank spaces
I confirmed this was working by running it locally.

Add a more generic warning about the default password

---

odk1-src/aggregate-forms.rst
odk1-src/form-update.rst

closes #902
In this PR:
- Fix a language nuance around blank form versions 
- Explains how blank forms downloaded from Aggregate can (and will) be different from the original blank forms that are uploaded

Issue 902 aggregate versions

---

odk1-src/form-question-types.rst

closes #908
Replace word `type` with `appearance` for range widget with `picker` appearance. 
None.
None.
None.

Correction for `picker` apperance documentation.

---

odk1-src/briefcase-using.rst

Closes #913, #914, #915, and #879 
- New CLI pull op `-ii` flag
- New CLI export op `-ig`, and `-rgn` flags
- New UI export conf option to include a GeoJSON companion
- Add note about split select multiples
- Explain what files can be generated when exporting forms
I'm not sure about the summary table in the last commit. Got any feedback?

Briefcase v1.13.0 changes

---

odk1-src/briefcase-install.rst

Document the solution at https://forum.opendatakit.org/t/odk-briefcase-not-setting-up-properly-after-download/16576. 
The cause seems to be OpenJDK does not include useful root certs.
We might want to put this language with the Aggregate as well? I'm not sure.

OpenJDK does not seem to include useful root certs

---

odk1-src/_static/css/custom.css
odk1-src/collect-filling-forms.rst
odk1-src/form-logic.rst
odk1-src/img/collect-forms/jump-button-add.png
odk1-src/img/collect-forms/jump-button-remove.png
odk1-src/img/collect-forms/jump-button-up.png
odk1-src/img/collect-forms/jumpicon.png
odk1-src/img/collect-forms/jumpmenu.png
odk1-src/img/collect-forms/jumpscreen.png
odk1-src/img/form-logic/jump-menu-groups.png

Addresses https://github.com/opendatakit/docs/issues/931
- Added `form-logic.html#groups-of-questions`
- Added `collect-filling-forms.html#adding-instances-of-looped-groups`
- With screenshot of "add" button
- Added `collect-filling-forms.html#removing-instances-of-looped-groups`
- With screenshot of "remove" button
- Updated `collect-filling-forms.html#jumping-to-questions`
- Updated the screenshots to show new icons and grouping
- Added screenshot of "up" button
- Linked to new `adding`/`removing` sections above
- ~~How do we explain to users what a `ref` is?~~
- ~~How do they add a `ref` in [Build](https://build.opendatakit.org/)?~~

Document "visible groups" in jump screen

---

odk1-src/form-logic.rst

Minor fix from a user comment at https://forum.opendatakit.org/t/unexpected-behaviour-of-the-now-function/17302

age should be a variable

---

odk1-src/central-projects.rst

updates one link in the central project documentation to point at the latest minor revision, as we just pushed a new one.

central: bump 0.4 beta version link to match the latest revision.

---

odk2-src/app-designer-install.rst

Looks like I needed an extra space in the to properly display the console text. It wasn't appearing properly in the final version.

app designer installation fix spacing

---

odk2-config/s3_website.yml

* Publish the docs to odk-x folder on S3. This folder has already been created.
* Redirect all incoming links form odk2 to odk-x
After merge:
1. Remove the CloudFront behavior redirection
2. Remove the odk folder on S3

Publish to odk-x directory, redirect incoming links

---

odk1-src/form-logic.rst

closes #961 
The faulty example is removed. I also simplified the language.

Remove incorrect now() example and simplify language

---

odk2-src/xlsx-converter-reference.rst

As per previous forum discussion: https://forum.opendatakit.org/t/xlsx-converter-typeerror-cannot-read-property-length-of-undefined/3234/9, this pull request changes an uppercase column heading to lowercase on an example settings sheet.
Should I open a new issue first?
closes #
addresses #
Changes an uppercase column heading to lowercase on an example settings sheet. This could prevent future user errors like https://forum.opendatakit.org/t/xlsx-converter-typeerror-cannot-read-property-length-of-undefined/3234/8. 
None.
The issue is addressed.
None.

Makes example column heading lowercase

---

odk1-src/briefcase-using.rst

* Moved form ID down to optional params and verified that is what the output looks like in Briefcase.
* Added the same warning that the pull from Collect has. I thought it was important to note that we can't pull all forms, just forms that Briefcase has access to.
* Confirmed that it looks good in a browser.

Form IDs are no longer required for pull

---

odk1-src/launch-apps-from-collect.rst

"If bundle" -> "If the bundle"
While I was there, I tried to make the sentence easier to parse.

Add missing word

---

odk2-src/sync-endpoint.rst
shared-src/spelling_wordlist.txt

Hello,
Sorry if I'm not following procedure - I am new to this, so please bear with me :)
I added a warning about Git for windows substituting LF with CRLF, since that will cause the containers to be unable to start. Perhaps it could be useful to someone else - it did at least cost me quite a lot of time to figure out that this was the issue ;-)
(on a side note; it is mentioned that sync-endpoints should be compiled with java jdk 8, but I could only get it working with jdk 12? If I used jdk 8, it crashed with a lot of "duplicate class definition" errors - this could however also be a side effect of my messing up of line endings with autocrlf=true in git)
A note in the documentaion

Added hint for using Git on windows

---

odk1-src/aggregate-deployment-planning.rst

Small change to address the issue raised at https://forum.opendatakit.org/t/installing-odk-aggregate-with-latest-support-packages/19928.

Clarify that we do not support MariaDB

---

odk1-src/central-install-digital-ocean.rst

closes #1036
updates the env names to match the current `.env`. also did a search through the rest of the docs for other instances and didn't find any.

central: bug #1036 / incorrect env names in digitalocean install.

---

odk1-src/form-update.rst
odk1-src/img/form-update/get-new-version.png
odk1-src/img/form-update/two-version-form.png

addresses #710 
The pr documents the change we implemented in collect:
-only the newest form version is displayed on the form list.
-updates have an additional message on the list of forms we can download

Only newest form versions is visible in Collect

---

odk1-src/form-audit-log.rst

Rename answer tracking to better match parameter
I did not do any redirects because I doubt there are any external links. This feature is new and unannounced.

Rename answer tracking to better match parameter

---

odk1-src/central-install-digital-ocean.rst

Stung by a config error leading to spurious [error messages in the frontend](https://github.com/opendatakit/central/issues/81), having Sentry error logging available is immensely useful. 
Addresses https://github.com/opendatakit/central/issues/81
An update to docs on how to configure own Sentry error logging.
Decide on best practice to configure Sentry logging:
Is hacking the default.json (as described in this PR - parallel to disabling Sentry) a good way, or should the docs advise to provide a custom Sentry config a local.json instead? The latter is how we run Central on Kubernetes.
A lack of logging (fixed by having own Sentry logs now) and a slow moment where I forgot to check `/var/log/(anything useful)` inside the running container. Needed a reminder from @issa-tseng which pointed me …

Include steps to use own Sentry error logging

---

.circleci/config.yml

closes #1085
I did a search and replace for `openjdk-8-jre-headless` to `openjdk-11-jre-headless`. I don't think there's a great way of verifying this other than merging and having it run on CircleCI.

Use JDK 11 because JDK 8 is no longer supported

---

odk1-src/form-operators-functions.rst

Closes #1070.
Documentation for the `normalize-space` function. See https://github.com/opendatakit/javarosa/pull/467

Add documentation for normalize-space

---

odk1-src/collect-offline-maps.rst
odk1-src/collect-settings.rst

closes #1073
Updates map settings and offline maps sections to match Collect v1.23. I tried to give a little help for folks on older versions.
I didn't add any screenshots because I don't think they are necessary. Let me know if you think otherwise. I considered adding an image for the layers button, though. Would that be helpful? I'm guessing folks who have the capacity to use offline tiles have seen gis software before and will recognize the layers icon but could be convinced otherwise.
I didn't go into too much detail about offline vector tilesets because we hope to improve that soon.
There's a bit of redundancy because I was trying to make each section stand alone. If this is bothersome, I can revisit.
I ran `make odk1-spell-check` locally and verified there were no spelling errors in …

Update map settings and offline maps sections for new Collect maps settings and Mapbox support for vector MBTiles files

---

odk1-src/launch-apps-from-collect.rst

Add text "Notice that the ex:prefix is not included" to Clarify that ex: prefix is only for external apps that populate one field.
closes #
addresses #

Clarify ex:prefix use

---

odk1-src/form-audit-log.rst

closes #1054 
It documents that changing audit log options for a form definition and then editing an existing record can result in a corrupt audit.

Warn that changing audit log options for a form definition and then editing an existing record can result in a corrupt audit

---

odk1-src/collect-offline-maps.rst

The link doesn't show up as clickable because there was a missing underscore.

Fix MBTiles metadata link

---

odk1-src/central-intro.rst

Addresses #1076 
We now support encrypted forms and ODK Briefcase v1.17 (which is ready, but hasn't been released) has push/pull support.

v0.6 supports encryption and push/pull for Briefcase

---

odk1-src/collect-forms.rst
odk1-src/form-question-types.rst
odk1-src/form-styling.rst
odk1-src/img/form-styling/audio-image.png
odk1-src/img/form-styling/video-image.png
shared-src/spelling_wordlist.txt

Closes #1112
Additional documentation (and some reworking) around using media (image, audio, video) in forms for Collect. 
I tried to think about the journeys for learning about adding media and was happy with "Form Styling" providing most of the info and also with having documentation around adding files themselves to a media folder living elsewhere. I've kept everything linked so the journeys through the docs work like this:
* Media -> Loading Form Media
* Loading Form Media -> Media
* Including Media in choices -> Media -> Loading Form Media

Add documentation for media and autoplay

---

odkx-config/s3_website.yml

- Fix build issue from https://circleci.com/gh/opendatakit/docs/4673 `[fail] Failed to push the website to http://odkx-docs-web.s3-website-us-west-2.amazonaws.com`

Use existing ODK2 bucket for now to fix build when pushing to S3

---

.circleci/config.yml

addresses #1127 
Fix to circleCI publishing to fix broken links to ODK-X's PDF documentation.

fix circleci posting of the pdf documentation

---

odk1-src/form-logic.rst
odk1-src/form-question-types.rst

Begins addressing #1016
How to frame the current limitations with `once` requires some thought but I want to make sure that it's clear that newer versions of Collect do support logic evaluation within a screen.

Logic within a field list is evaluated in Collect v1.22+

---

odk1-src/form-operators-functions.rst

`1` is missing and `2` is repeated

xlsform example typo fix

---

odk1-src/collect-offline-maps.rst

Remove mention of openmaptiles.org for now because it only provides vector mbtiles. Emphasize that users will generally want raster mbtiles files.
CC @batkinson

OpenMapTiles only serves vector mbtiles so remove it

---

odk1-src/form-question-types.rst

The option text for Likert does wrap as shown in the screenshot ("Strongly Agree" is broken into two lines).

Likert option text does wrap

---

odk1-src/collect-form-map.rst
odk1-src/collect-forms.rst
odk1-src/collect-using.rst

closes #1144
I didn't add any screenshots because they add a maintenance burden, make it harder to scan and I think that in this case text is sufficient to describe what's going on. If reviewers think it would be helpful to have some visuals, let me know.
I tried to be really thorough about documenting all states that forms could be in and what the behavior should be. Gaps there would be something to look for.
I also tried to link out to any related documentation.
FYI @zestyping if you're interested in taking a peek.

Add form map documentation

---

odk1-src/form-audit-log.rst

Closes #1155.
A new section in the form audit docs around `identify-user`. Was originally thinking of including screenshots but not sure we need it for this. Interested in if others disagree!

Add identify user/track changes reasons docs

---

odk1-src/form-logic.rst
odk1-src/form-operators-functions.rst
odk1-src/form-repeats.rst
odk1-src/incl/form-examples/parallel-repeats.rst

closes #1042
- an introduction to repeats
- a rework of the repeat count tip which wasn't right
- links between the repeat tips and repeat introduction sections
- an example for indefinite repeats (#1042)
- an example for 0 or more repeats
I'd like to keep adding recipes but I think this adds a lot of value already.
We're doing this now in the context of @seadowg taking a look at the repeat user experience in Collect.

Clean up repeats section and add recipes for avoiding dialog

---

odkx-src/select-tool-suite.rst
shared-src/docs-tech-guide.rst

addresses #823 & #96
I added a note to the Docs Contributor Technical Guide that the Python tools necessary to install 
to edit the docs are incompatible with Windows 10 Home. Also, I edited the ODK-X Selecting the Appropriate Tool Suite "Trying Them Out" section to remove jargon. 
If possible, modifying Sphinx to replace the pyenchant 2.0.0 Python tool with a similar tool that does not cause issues for Windows 10 Home users.

Adding a note for Windows 10 users and a line edit.

---

odk1-src/form-logic.rst

Adds documentation for dynamic defaults and last-saved.
I decided to put the version requirements in warning blocks in this case because using dynamic defaults or last-saved with tools that don't support it will have unpredictable results.
I'd like to add a section about dynamic defaults in repeats but so far the examples I've come up with either require writing XPath expressions like `if(position(..) >= 1, /data/child_details[position() = position(current()/..) - 1]/child_school, '')` or suffer from the issue I described at https://github.com/XLSForm/pyxform/issues/182#issuecomment-583560793. There's also a bug I discovered at https://github.com/XLSForm/pyxform/issues/427. So I think we should come back to that.

Dynamic defaults and ${last-saved#question_name}

---

odkx-src/advanced-topics-architect.rst
odkx-src/app-designer-intro.rst
odkx-src/build-app.rst
odkx-src/cloud-endpoints-intro.rst
odkx-src/cold-chain-tour-initial-data.rst
odkx-src/episample-tour-household-survey.rst
odkx-src/getting-started-2-architect.rst
odkx-src/getting-started-2-user.rst
odkx-src/index.rst
odkx-src/scan-form-designer-intro.rst
odkx-src/scan-intro.rst
odkx-src/select-tool-suite.rst
odkx-src/services-intro.rst
odkx-src/services-using.rst
odkx-src/suitcase-intro.rst
odkx-src/survey-intro.rst
odkx-src/survey-sample-app-end.rst
odkx-src/survey-sample-app.rst
odkx-src/tables-intro.rst
odkx-src/tables-managing.rst
odkx-src/tables-sample-app-end.rst
odkx-src/tables-sample-app.rst
odkx-src/tables-using.rst
odkx-src/xlsx-converter-intro.rst

addresses #1139
As a beginning step in revising the ODK-X Docs learning paths, I went through and removed the "Deployment Architect" jargon, and reorganized the sections to be more consistent with the ODK Docs flow. 
The learning paths need to be further revised to simplify and to remove redundancies.

I edited the ODK-X docs to remove "Deployment Architect" language.

---

odk1-src/form-question-types.rst

A user ran into this at https://forum.opendatakit.org/t/background-geopoint-error-in-aggregate-server-on-form-upload/24983/3?u=ln
Central version doesn't matter.

Add min Aggregate version for background geopoint

---

odk1-src/form-logic.rst

Augment last-saved documentation based on feedback at https://forum.opendatakit.org/t/some-feedback-on-the-last-saved-feature/24818
@danbjoseph it would be great to get your review! Let me know if you see any other gaps.

Clarify that last saved references can be used anywhere

---

odk1-src/briefcase-using.rst
odk1-src/collect-adb.rst
odk1-src/collect-forms.rst
odk1-src/collect-offline-maps.rst
odk1-src/xlsform.rst

Users of Collect from the Play Store will need to move their files to a scoped directory by August 2020. The migration will start being available in Collect v1.26.0. This PR replaces all references to `/sdcard/odk/`.
I searched the `odk1-src` directory for `/sdcard` and `/odk` and made replacements as appropriate. I decided to leave the .settings file documentation alone because it will get removed by #1192.

Update references to the Collect root directory in preparation for the scoped storage migration

---

odk1-src/collect-settings.rst
odk1-src/img/collect-settings/server-settings.png
odk1-src/img/collect-settings/ui-settings.png

Closes #1181 
Closes #1165
While I was there, I also made every setting into a heading so that they can be linked to directly. This is something I've often missed when offering support. I also collapsed some screenshots that don't add a lot to clear the visual clutter.
All images were run through ImageOptim.

Document installID, guidance hints, form updates

---

odk1-src/collect-settings.rst

When compiling https://forum.opendatakit.org/t/proposal-publish-a-settings-key-value-standard/25142, I noticed that some settings are not described in enough detail to understand their behavior.

Add more details to settings descriptions

---

odk1-src/collect-import-export.rst

I was getting an error related to "JSON". It turned out it was due to the `code-block` but I changed JSON to "foo" to troubleshoot and apparently didn't change it back.

Replace errant 'foo'

---

odk1-src/collect-import-export.rst

This was wrong. See https://github.com/opendatakit/collect/blob/8cd8a91f269c4515621075efb2de3006d0c21b30/collect_app/src/main/java/org/odk/collect/android/preferences/GeneralKeys.java#L79.

Fix Carto map style preference key

---

odk1-src/central-install-digital-ocean.rst

Closes #1200
* Add SMTP auth settings
* Makes sure code blocks line up under the text it refers to.
* Add JSON metadata. No user-visible change.
You can confirm this all works:

Add Central SMTP auth details

---

odkx-src/sync-endpoint.rst

closes #1197 
An update of the minimum recommended version of Docker for ODK Sync Endpoint.

Bump minimum recommended version for Docker

---

requirements.txt

A new version of `setuptools` was released that deprecates "Feature" which was used by MarkupSafe. See https://github.com/pypa/setuptools/issues/2017#issuecomment-596307305 and pallets/markupsafe#57.

Update MarkupSafe to fix build

---

odk1-src/central-forms.rst
odk1-src/central-install-digital-ocean.rst
odk1-src/central-intro.rst
odk1-src/central-projects.rst
odk1-src/img/central-forms/attachments-listing.png
odk1-src/img/central-forms/attachments-multi.png
odk1-src/img/central-forms/attachments-overview.png
odk1-src/img/central-forms/attachments-single.png
odk1-src/img/central-forms/checklist.png
odk1-src/img/central-forms/draft-overview.png
odk1-src/img/central-forms/testing.png
odk1-src/img/central-forms/update-form.png
odk1-src/img/central-forms/versions.png

closes #1212
adds documentation on form draft/versions/testing
adds documentation on enabling digital ocean monitoring for disk utilization

[Central] updated documentation for block 8 release

---

odk1-src/_static/css/custom.css
shared-src/_static/img/odk-logo-wide.png

Tried to match the size to the forum logo. I eyeballed it.
Changed the docs color to white to match the default look of Sphinx.

Smaller and white logo

---

odk1-src/collect-settings.rst

This came up in conversation with @seadowg who is working on the match exactly feature. Initially I couldn't remember why we'd separated out update checks from downloads. I now recall that there was an ask (from the TSC, I think) for users to be able to still control the download.
More documentation on existing automatic form update features.

Clarify periodic check and auto download behavior

---

odk1-src/central-install-digital-ocean.rst

https://www.digitalocean.com/community/tutorials/how-to-set-up-a-host-name-with-digitalocean doesn't work anymore
i think https://www.digitalocean.com/community/tutorials/how-to-point-to-digitalocean-nameservers-from-common-domain-registrars is  the equivalent?

fix DigitalOcean tutorial link

---

odk1-src/collect-import-export.rst

At:
https://forum.getodk.org/t/qr-code-contains-no-information-about-google-map-style/28289/2
I've noticed that the [ODK documentation](https://docs.getodk.org/collect-import-export/#list-of-keys-for-all-settings) is outdated for some key values. I'm changing some values I've found decoding de configuration QR code generated by ODK Collect.
>// Server
>"protocol": {"odk_default", "google_sheets", "~~other~~"} ---> must be substituted by **other_protocol**
>
>// Form management
>"guidance_hint": {"no", "yes", "~~collapsed~~"} ---> must be substituted by **yes_collapsed**
I haven't checked other values, so there may be other cases. I'll let you know if I find anything else.

Fix for outdated key values in the list for all QR code settings

---

odk1-src/openrosa-metadata.rst

closes #1239
changed namespace prefix to avoid confusion since `jr:` is used for other namespaces in ODK XForms documentation

Changed metadata namespace prefix used to avoid confusion, closes #1239

---

odk1-src/central-install-digital-ocean.rst

Add a bit more detail around what the `.pem` files should contain to help users troubleshoot problems like https://forum.getodk.org/t/enketo-certificate-issue-on-central-0-9/28578.

Add details for custom SSL cert files

---

odk1-src/central-submissions.rst

Update links from DBCA to ROpenSci (redirects do not support rOpenSci's custom domain)
closes #1248 
Updated links, unchanged text.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/getodk/docs/1249)

Update ruODK links in central-submissions.rst

---

odk1-src/collect-form-map.rst
odk1-src/img/collect-forms/form-map-with-selection.png

closes #1224
I optimized the screenshot with ImageOptim. I added details about how to use the `instance_name` for the bottom sheet to display useful information.
I linked out to the XLSForm "spec" about `instance_name` for now. I think it would be good to have a section about the settings sheet with more narration around what should be set and why. I filed #1261

Describe bottom sheet for form map

---

odk1-src/form-question-types.rst

Removes unique IDs that Android prevents access to when targeting Android 29+.
More at https://github.com/getodk/xforms-spec/pull/275. I think that for this user-facing documentation, we can simply remove these and don't need to wait for how versioning should work at the spec level.

Remove unique IDs that are no longer accessible

---

odk1-src/central-install-digital-ocean.rst
odk1-src/central-install.rst
odk1-src/central-intro.rst
odk1-src/central-setup.rst
odk1-src/central-troubleshooting.rst

We need to be explicit that the core team has limited ability to verify Central releases on platforms other than Digital Ocean and that we generally won't be able to provide free support for custom installs.
I tried to make the message direct but still friendly. I went with "community support" but also considered "free support". I considered saying "because Central is developed by a small team" or something like that but it didn't seem all that useful.

Describe limited support for Central on environments other than DO

---

odk1-src/central-backup.rst

We've gotten various questions about Central backups and where they send data (e.g. https://github.com/getodk/central/issues/167). This PR clarifies that managing external backups is a possibility and may be a better option for a lot of folks.

Add background on Central backups

---

odk1-src/aggregate-app-engine-legacy.rst
odk1-src/aggregate-setup.rst
odk1-src/central-api.rst
odk1-src/central-command-line.rst
odk1-src/central-install-digital-ocean.rst
odk1-src/central-install.rst
odk1-src/central-upgrade.rst
odk1-src/collect-connect.rst
odk1-src/collect-install.rst
odk1-src/getting-started.rst

* Removed references to the Central and Aggregate sandboxes
* Added language about ODK Cloud and made it an top-level item for visibility
* Flipped order of getting started to start with Central, then Collect
* Cleaned up lots of extra "ODK tool" names
* Cleaned up Play Store links

Remove sandboxes, add ODK cloud, remove extra ODKs

---

src/form-logic.rst
src/form-question-types.rst

closes #1267
I added two warnings in the docs to make it clear that we don't support having repeating questions inside field-list groups

Added warnings to make it clear that we don't support having repeating questions inside field-list groups

---

src/briefcase-install.rst

We know there are some issues with running Briefcase with Java 8. Java 11 has been available since 2018 and has LTS so it's the version most people should use.

Recommend Java 11 for Briefcase

---

src/_templates/footer.html
src/conf.py

* Simplify the footer structure. Not sure why it is so complex to begin with.
* Reduce the copyright to the bare minimum notice (https://www.copyright.gov/circs/circ03.pdf)
* The theme doesn't require attribution (as determined by skimming https://sphinx-rtd-theme.readthedocs.io/en/latest/index.html and the existence of the show_sphinx variable (which doesn't seem to work))

Cleanup footer

---

src/form-logic.rst
src/img/form-logic/repeat-iteration-modal.png

Now available in pyxform 1.3.1. I also fixed some outdated text in the repeat section and updated a screenshot. I used `ImageOptim` on the image.

Document select_one from repeat

---

src/form-question-types.rst
src/img/form-widgets/select-grid.png

Closes #1195
I didn't think it was necessary to show an example of `list`. I've never actually seen a practical example of it.

Add practical example of select grid

---

src/form-logic.rst

closes #1176
Adds example of dynamic defaults across repeat instances.
Also replaces the section on `once` with a section on using `trigger` for dynamic defaults on value change.
I built and looked at this locally. I tried the sample forms in Collect v1.29-beta.1.

Document dynamic defaults across repeat instances and on value change

---

src/form-logic.rst

closes #1296 
Previously the example erroneously suggested that `. < 20 and . > 200` would evaluate to True  if the value was between 20 and 200. In actuality, this would evaluate universally to False. I switched around the direction of the greater/less than symbols.

Corrected greater than less than condition example

---

src/central-troubleshooting.rst

I didn't notice that the last PR didn't build on CI and I merged despite spelling errors.

Fix spelling

---

src/central-install-digital-ocean.rst

Currently, Central checks the local DB before starting. If we have a custom DB, we should check that DB instead.
I'm not sure if this is the best approach to do that (e.g., maybe we can set the host:port as a variable somewhere), but I figure having something in the docs is better than nothing.
I did not verify this change actually works.
I considered adding language to remove all the Postgres container stuff from the docker-compose file, but the container itself is small, and big changes to docker-compose will likely result in merge conflicts for folks, and documenting both the how to remove things and the support burden of merge conflicts seems not worth it.

Wait for custom db, not bundled db

---

src/collect-filling-forms.rst
src/img/collect-completing-forms/question-screen-with-buttons.png
src/img/collect-forms/jumpscreen.png
src/vid/collect-completing-forms/swipe-example.mp4

* Clarifies that buttons and swipes is now the default navigation mode
* Refers to the next and back buttons as "next" and "back"
* Updates screenshots that include the next and back buttons
* Removes swiping video
The video didn't seem very useful to me so reclaiming the space felt worth it.
Images went through ImageOptim.

Update buttons and swipes functionality

---

src/central-troubleshooting.rst

We should order troubleshooting help by most likely first. This is more important here because database disappearance is scary.

Order help by most likely first

---

.circleci/config.yml

Builds with ruby v3 will fail on `s3_website install` with..
```
[info] Downloading https://github.com/laurilehmijoki/s3_website/releases/download/v3.4.0/s3_website.jar into /usr/local/bundle/gems/s3_website-3.4.0/s3_website-3.4.0.jar
/usr/local/bundle/gems/s3_website-3.4.0/bin/s3_website:253:in `initialize': No such file or directory @ rb_sysopen - https://github.com/laurilehmijoki/s3_website/releases/download/v3.4.0/s3_website.jar (Errno::ENOENT)
from /usr/local/bundle/gems/s3_website-3.4.0/bin/s3_website:253:in `open'
from /usr/local/bundle/gems/s3_website-3.4.0/bin/s3_website:253:in `block in download_jar'
from /usr/local/bundle/gems/s3_website-3.4.0/bin/s3_website:252:in `open'
from /usr/local/bundle/gems/s3_website-3.4.0/bin/s3_website:252:in `download_jar'
from …
```

s3_website doesn't work on Ruby v3

---

src/central-install-digital-ocean.rst

* I prefer Ubuntu's instructions because seems likely to be a better source of truth
* Add swap to fstab! Not sure how we missed this.
* Reducing the swappiness of swap so it's only used when absolutely necessary. Default is 60.

Improve swap commands

---

src/central-install-digital-ocean.rst
src/central-troubleshooting.rst
src/form-question-types.rst

Closes #1295 
Closes #1294
Central troubleshooting section about corrupt exports, Central troubleshooting section about max upload size, tip about video file size.
I decided to change our swap recommendations. Since memory usage can be unpredictable, it's a nice protection to have, and we do this for every server we set up. With a low swapiness, the performance impact should be minimal. Paired with monitoring, it gives server admins an opportunity to make adjustments to available memory without having to experience crashes.
I built and looked at the results locally.

Add troubleshooting section about corrupt exports

---

src/form-audit-log.rst
src/form-logic.rst

closes #1292
The primary goal of this PR is to add a section on light weight timestamping. I also added some general context on the `trigger` column and made light improvements to the audit docs.
I'm not entirely satisfied with where the `Triggering calculations on value change` section ends up. It's certainly not as important as constraints, etc. Ideally we'd have a page for calculates that would progress into more advanced uses such as this. Given the current monolithic form logic page, I think this is reasonable.

Describe lightweight timestamping

---

src/form-question-types.rst

To be shipped with Collect v1.30
I recommend looking at the two commits separately. There's a little bit of redundancy with the foreground audio section but I couldn't find smooth ways to link between them. This feels ok and I think it's fine if the wording ends up deviating a little bit.
Any screenshot needed? I've gone back and forth on adding one of the top bar.
TODO:

Add background audio documentation

---

src/aggregate-admin.rst
src/aggregate-app-engine-legacy.rst
src/aggregate-app-engine.rst
src/aggregate-aws.rst
src/aggregate-azure.rst
src/aggregate-backup.rst
src/aggregate-best-practices.rst
src/aggregate-boost-performance.rst
src/aggregate-data-access.rst
src/aggregate-data.rst
src/aggregate-deployment-planning.rst
src/aggregate-digital-ocean.rst
src/aggregate-field-length.rst
src/aggregate-forms.rst
src/aggregate-google-cloud.rst
src/aggregate-help.rst
src/aggregate-install.rst
src/aggregate-intro.rst
src/aggregate-limitations.rst
src/aggregate-setup.rst
src/aggregate-tomcat.rst
src/aggregate-upgrade.rst
src/aggregate-use.rst
src/aggregate-visualize.rst
src/aggregate-vm.rst
src/form-question-types.rst
src/form-update.rst
src/security-privacy.rst
src/xlsform.rst

* Add "ODK" to Aggregate deprecation note to make for more balanced wording
* Remove description of XLSForm Offline
* Remove all references of XLSForm Offline versions because we don't want people using it
* Remove instructions for pyxform in favor of direct links
* Document the preferred way to design forms (upload them to Central)
* Explain when you'd want to use XLSForm Online and pyxform
The form design intro page is horrible still, but we'll save that for another day.

Update Aggregate language, remove XLSForm Offline

---

src/central-install.rst

I have personally use this AMI and the instructions, so I know they work!

Ubuntu 16 is no longer the recommended LTS

---

src/collect-settings.rst
src/encrypted-forms.rst
src/form-design-intro.rst
src/form-language.rst
src/form-logic.rst
src/form-question-types.rst
src/xlsform.rst

Closes #1261 
The high-level goal of this PR is to document the `settings` worksheet in XLSForm. The immediate need this satisfies is to have something useful to link to from [Central submission details page docs](https://github.com/getodk/docs/pull/1346#discussion_r625222771).
I also took the opportunity to take care of various things we've been wanting to do for some time:
- I linked to an XLSForm template. I'm pretty confident in the columns I included but if it seems controversial, we could pull it for now and have some more discussion. I don't think we want to change the column order once we publish.
- Cut out a bunch of things from the encryption page. It needs to be written but this is a quick move towards that.
- Add a high-level introduction to forms that is aimed at project …

Provide general introduction to XLSForm, add starter template

---

src/central-install-digital-ocean.rst
src/central-intro.rst
src/central-server-audits.rst
src/central-submissions.rst
src/central-upgrade.rst
src/img/central-install/nano.png
src/img/central-submissions/details.png
src/img/central-submissions/download-button.png
src/img/central-submissions/listing.png
src/img/central-submissions/new.png
src/img/central-submissions/odata-button.png

the three commits describe what happens here:
1. update the `.env` and install documentation to account for those changes.
2. update the submissions docs w newer screenshots, and add information about the new details page and features.
3. update the audit log actions list.
anything i missed?

Update documentation for Central v1.2

---

src/central-submissions.rst

We get this support issue not infrequently. Rather than put a list of steps that will vary per version of Excel (e.g., https://stackoverflow.com/a/6488070), I tried to find a Microsoft.com resource that describes the steps and put the important hints (e.g.,if you have accents, you need to import and specify file origin) in the text I wrote.

Warn users about CSV imports in Excel

---

src/collect-adb.rst
src/collect-connect-google.rst
src/collect-connect.rst
src/collect-projects.rst
src/collect-using.rst
src/getting-started.rst
src/img/collect-projects/main-menu-with-project.png

Work towards #1365
Update ODK "Getting Started" and Collect's "Connecting to a Server" for Projects and add the beginning of a "Managing Projects" page. This doesn't address everything we need to update and there is still more to document on Projects themselves, but I think it's a good start and makes sure new users aren't looking at out of date setup instructions.

Update Collect setup for projects release

---

.circleci/config.yml
Makefile
requirements.txt

I can confirm that image-resizing (pillow) and spell-checking (pyenchant) both work.

Upgrade and fix Python versions for more predictable builds, move packages to userland

---

src/form-question-types.rst

Constraining location accuracy is very useful and I needed an obvious place to put it. I find the existing tip not that useful (except for maybe the bit about devices having a clear view of the sky).
I added a bit more information to the overall note about accuracy
Then added the selected-at tip.

Accuracy tip for geopoint

---

src/collect-connect.rst

It feels like this should have thrown an error somewhere. Anyway, this specific instance has been fixed.

Fix broken links

---

src/form-question-types.rst

We have a customer who has had crashing issues with RecForge. See https://forum.getodk.org/t/issues-with-audio-recording/35116/3 for more. 
I have confirmed that RecForge crashes on v2021.2.4. It's a very ad-heavy app so rather than track down the issue, I think we should remove it. I have confirm that axet's call record works great on my Pixel 3a running Android 11.
And while I was there, I think we should recommend people use the built-in audio recorder, so I've moved some of the language around. 
Things to consider for review:
- I'm not sure why we didn't do this originally. Maybe our audio recorder is terrible for older versions of Android? I don'
- I tried with a few other apps (Smart Recorder, Audio Recorder - no ads) but none of them showed up on the dialog Collect presents to …

Default to built-in audio recorder, remove RecForge recommendation

---

src/central-upgrade.rst

Since docker-compose instructions are below the generic upgrade instructions, users won't know about the required version before upgrading. This ensures they see that information first.

Ensure users read version-specific instructions

---

src/form-question-types.rst

or_other doesn't have [language support](https://github.com/XLSForm/pyxform/issues/218) or [choice_filter](https://github.com/XLSForm/pyxform/issues/17) support and people should know that. We should probably deprecate it at some point.

or_other should not be used due no language or choice_filter support

---

Dockerfile

closes #1418 
Update to base python version in Dockerfile
Determine whether pinned python version is appropriate

Pin python version in Dockerfile to avoid 3.10 compatibility issues

---

src/form-datasets.rst

closes #1437
Adds a brief note to the Form Datasets documentation regarding the fact that a `choice_filter` value is required when referencing internal data instances.
I missed the [existing note about this behavior](https://github.com/getodk/docs/blob/master/src/form-logic.rst#dynamic-defaults-from-form-data) on the Form Logic page and was [very confused](https://forum.getodk.org/t/referencing-values-in-internal-datasets/36874) about why my minimal form configuration did not work.

Add note about `choice_filter` when referencing internal instances

---

src/central-encryption.rst
src/central-forms.rst
src/central-submissions.rst
src/img/central-encryption/decrypt.png
src/img/central-forms/trash.png
src/img/central-submissions/download-modal.png

Adds information about the new export options and form deletion cycle. Patches a couple old spots that referenced downloads.

central: documentation for version 1.4.

---

src/index.rst
src/training.rst

My initial goal is to provide information that is ODK-centric (e.g., not Aggregate or Survey123 or KoBo) and is up-to-date. I think it's important to summarize each link and provide the media type and date and so I've done that.
I cheat a bit with xlsforms.org date, but I think I can be forgiven.
I'm very open to changing any of this.

Add up-to-date training resources

---

src/form-question-types.rst

closes #1435
I've added a warning which explains the rare case with producing bigger output images that might take place using max-pixels

Explain the rare case with bigger output images using max-pixels

---

src/form-logic.rst

closes #1340 
Added a warning which clarifies that last-saved won't work with binary attachments:

Last-saved won't work with binary attachments

---

src/conf.py

enchant requires an Intel chip (https://pyenchant.github.io/pyenchant/install.html?highlight=silicon#on-macos) and I'd rather not install the Intel version of brew just for this. I also don't love using the Docker build.
This PR skips spellcheck when on Apple Silicon.

Skip spellchecking on Apple Silicon because enchant requires Intel chip

---

src/briefcase-api.rst
src/briefcase-install.rst
src/briefcase-intro.rst
src/briefcase-using.rst
src/index.rst

Same thing we did with Aggregate
* Add a message to the top of all pages.
* Remove from table of contents
* Add orphan tag so build completes
All this ensures that the pages are hidden, but links work. There will still need to be some clean up of mentions of Briefcase and Aggregate.

Deprecate Briefcase

---

docs/_static/css/custom.css
docs/collect-settings.rst
docs/form-language.rst
docs/form-logic.rst
docs/form-operators-functions.rst
docs/form-question-types.rst
docs/form-styling.rst

Closes https://github.com/getodk/docs/issues/576
Collect screenshots have been huge for a long time. This became even more apparent with the new, cleaner theme. I don't see a good reason to ever see them with more than 400px of width.
There already was a `device-screen-vertical` class applied to some vertical device screenshots. I set that width to 400px and applied the class more thoroughly. I briefly considered adding a new directive but using a modifier on the standard directives ended up feeling better.
I searched for the `image` and `figure` directives in docs related to Collect. I went pretty quickly and then I rendered the pages and scrolled through them to make sure my change was complete and didn't apply to other types of images.

Scale down vertical device images

---

docs/launch-collect-from-app.rst

closes #1376
It adds a warning that clarifies that launching Collect activities using their names is not supported

Explicitly state that launching Collect activities using their names is not supported

---

docs/central-install.rst

AWS defaults to 8 GB boot drives. That's too small for Central.
As promised at https://forum.getodk.org/t/central-using-lots-of-disk-space/39527/3, here's a PR to set a more reasonable minimum.

Suggest minimum disk size for AWS

---

docs/central-datasets.rst

I think quick start shouldn't have a long title because it's nicer as a link.
Testing seems more like a sub-section to datasets and entities in v2022.3
Sections after building sub-sections seemed like they should be sub-sections, so I've done that.
I've also tried to standardize case for Datasets and Entities in titles. Form maybe should be title case, but I don't feel strongly about it.
We could probably drop "Creating forms to use Datasets and Entities" as a section and bring "Building a form that creates" and "Building a form that uses" up a section.

Tweak datasets structure

---

docs/form-question-types.rst

closes #1518
The note looks like this:

Add a note about ignoring choices with invalid geometries

---

docs/central-forms.rst
docs/central-submissions.rst
docs/img/central-submissions/download-modal.png

Updates the section on submission exports to match new language. Adds a section header so we can directly link to export options. Crosslinks with form updates.

Add direct link to export options

---

docs/collect-offline-maps.rst

closes #1527
I've added a note in https://docs.getodk.org/collect-offline-maps/#transferring-offline-tilesets-to-devices which looks like:

Update offline maps section for projects

---

docs/collect-forms.rst

closes #1367
I've updated the note in https://docs.getodk.org/collect-forms/#editing-saved-forms so that now it looks like:

Describe that failed submission can't be edited but can be revieved

---

docs/form-logic.rst

I cleaned up the refs to make them more consistent (and match XLSForm).

Using notes instead of constraints, none and no other selections

---

docs/form-language.rst
docs/form-question-types.rst
docs/form-styling.rst

The `media::` prefix is really just a `pyxform` implementation detail. It leads to issues like https://github.com/XLSForm/pyxform/issues/601 so better to remove, especially since https://xlsform.org/en/#media doesn't use it.
I did `grep -r "media::" .` from the root and verified that no `rst` docs have it.

Remove media:: prefix for image, audio, video

---

docs/form-logic.rst

The error that the warning mentions definitely does not occur. There's a small chance that this is a change in behavior but I'm not sure.
One surprising thing about that example is that if a is 2 and b is blank, a_plus_b is blank. It might be expected to be 2 (and in fact, that might be the expected W3C XForms behavior, I'm not sure, JR's type coercion is not great).

Remove warning that is not or no longer true

---

docs/form-datasets.rst

closes #1488
It adds a note in https://docs.getodk.org/form-datasets/#building-selects-from-geojson-files which looks like this:

Document styling markers

---

docs/central-upgrade.rst

Goals:
- Make it easy to copy shell commands
- Improve the experience for people who upgrade every time
- Make it clear that instructions for every version between the current and target upgrade version are relevant
- Match https://docs.getodk.org/central-troubleshooting/#database-reset-after-running-docker-command which @yanokwa recently restructured
Todo:
- Add general instructions for performing maintenance: make a backup, announce a maintenance period, etc
@yanokwa, @alxndrsn, I'm interested in your early thoughts. I think this structure will make it easier to make the postgres upgrade instructions visible.

Update Central upgrade instruction structure to make commands copiable + draw attention to relevant version upgrade notes

---

docs/central-users.rst
docs/collect-import-export.rst

I struggled with where to place this and how to phrase.
Central's App User mode links to collect-import-export so I decided to put this text there there as a tip so it's more visible. For those who are coming from central-users I used "distribute" to give them a hint to click through.
I've tried to standardize where we use "QR code" vs "image" to make the docs more consistent. I think it's important to say "as an image" so people don't try to distribute screenshots which won't work as attachments. I didn't use "as a GIF" because that feels a little more technical and Collect doesn't use that term.

Add hint for how to distribute QR codes

---

docs/form-question-types.rst

It's just a small fix. In all other places, the table is called `survey` or `choices` to represent the names we use in xlsx.

Fixed name of csv table

---

docs/central-install-digital-ocean.rst

For some reason I thought we had managed not to require this for fresh installs but we didn't so it needs to be documented.

Add touching the postgres14 file to install

---

.circleci/config.yml

Thanks to @ivoanjo's work on s3_website we can upgrade to Ruby 3.2 and Java 11!
Verified working because I used the same code on https://getodk.org.
See https://app.circleci.com/pipelines/github/getodk/website/466/workflows/9ef42bda-0b8e-419b-b528-d650ef8b9f64/jobs/1073.

Updated build env and publish deps

---

docs/collect-settings.rst
docs/img/collect-settings/form-metadata.png

I've updated [Form metadata settings](http://localhost:8000/collect-settings/#form-metadata-settings) according to the current state of ODK Collect. It looks like [Metadata](http://localhost:8000/form-question-types/#metadata) does not require any changes.

Updated 'Form metadata settings'

---

docs/form-language.rst

I had a user ask about how to get Arabic and English in a form. 
I said the following...
> The Arabic column in the form should be RTL and the English column should be LTR. I think Excel will automatically do the right thing if Arabic is the only text cell.
> 
> Tell your Arabic users to set the mobile device or Collect language to Arabic so the app UI is RTL. Then they should set their form language to Arabic and the form text will also be RTL.
I want to add a small hint to the docs for RTL speakers.

Add RTL hint

---

docs/central-upgrade.rst

As of https://github.com/getodk/central/pull/428, we pin all base images to minor versions. The goal is for hosters to get patches at time of upgrade.
I considered adding `pull` for all the sections in https://docs.getodk.org/central-install-digital-ocean/#advanced-configuration-options and https://docs.getodk.org/central-troubleshooting/ The nice thing with that is there would be more opportunities to get point releases. But all of those are rare so it doesn't seem worth possibly adding a confusing setep.
<S>
My understanding is that this is what the `--pull` option for `build` does and that `docker compose pull` would not update base images. https://github.com/docker/compose/issues/2742#issuecomment-180077368
</s>

Add pull option to docker compose build

---

docs/central-upgrade.rst

Closes #1612 
The ongoing challenge is that we're going to need folks who aren't yet at 2023.2 to follow v2023.2 instructions. We could lump it in with our "follow instructions for all intermediary versions" guidance but this feels different to me. In particular, it doesn't feel obvious at all that following the v2023.2 instructions would lead to v2023.3 being installed with no further action needed. I tried to make that as clear as possible.

Add v2023.3 install instructions

---

docs/launch-collect-from-app.rst

closes #876
We have recently merged https://github.com/getodk/docs/pull/1605 so adding info about fetching the list of forms with only the newest version was the only missing element.

Document how to fetch the list of forms with only the newest version

---

docs/security-privacy.rst

I noticed this extra sentence was no longer correct.

Crash logging can now be disabled alongside analytics

---

docs/central-upgrade.rst

We had a user who upgraded from a very old version of Central and accidentally followed the upgrading from v2023.2 instructions. 
In this PR, I've flipped the order of the instructions to reduce the chance of this happening again. I've also made the titles a little more explicit.

Flip order of upgrade tabs to reduce confusion

---

Makefile

This fixes infinite watch loop for sphinx-autobuild, which looks for changes in `docs` directory and custom openApi extension also add/updates files in the same directory so we want to ignore watching autogenerated pages

add autogenerated page to ignore list for sphinx-autobuild

---

docs/central-install-digital-ocean.rst

Not a breaking change. https://nodejs.org/docs/latest-v18.x/api/cli.html#options says both `_` and `-` are supported. But `-` is what the docs say, so we should use that.

Update variable name

---

docs/central-install-digital-ocean.rst
docs/central-troubleshooting.rst
docs/central-upgrade.rst

This key needs to read by the Debian-exim user in the mail container. 
Currently, the key is mounted as [read-only](https://github.com/getodk/central/blob/master/docker-compose.yml#L33). And it inherits whatever permissions it has on the host, but there's no easy way to chgrp the file as part of mounting. 
~~The likely best way is to do so in the entrypoint.sh of the container ([example](https://github.com/ix-ai/smtp/blob/master/entrypoint.sh#L54C8-L54C19)), but I don't want to make upstream changes. I also don't want to have some command file in the docker-compose.yml~~
I've decided to be the change, and I've patched this upstream at https://github.com/ix-ai/smtp/pull/27.

Improve DKIM support

---

docs/central-entities.rst
docs/central-intro.rst
docs/img/central-entities/intro-diagram.png

Do not merge until Central v2023.4 and pyxform 12.1.2 are released!
Closes https://github.com/getodk/central/issues/466
I made a few cosmetic changes as I went, I don't think any should be controversial! @matthew-white and @ktuite, I'll let you two decide who most wants to review this. @ktuite at some point we should talk about whether we should consider updating your video. It's still very relevant! But the change in terminology is a bit distracting.

Replace Dataset with Entity List

---

docs/_static/api-spec/central.yaml
extensions/openapi/schema.mustache
extensions/openapi/spec_processor.py
extensions/openapi/table.mustache

- Render standard and extended responses schema/example. Achieved by showing multiple tabsets - screenshot at the bottom
- Request parameter description now supports markdown, so code is now rendered as `code` + other features of MD
- other minor improvements

Fix extended response

---

docs/form-question-types.rst

OMK has been sunset by American Red Cross (the original project owners), the fork of the server by HOT OSM last had a release update in Nov 2019, when Google changed how Android apps store/share data it broke how ODK and OMK communicated. i think the project is dead and this reference can be removed from the ODK docs.

remove OpenMapKit reference

---

docs/index.rst

I thought it'd be helpful to surface pyODK. Maybe it should be under the ODK Central API docs?

Add pyODK link

---

docs/collect-filling-forms.rst
docs/collect-forms.rst
docs/data-collector-workflows.rst
docs/img/collect-filling-forms/mark-form-as-finalized.png

@alyblenkin mentioned that "mark as finalized" doesn't make as much sense now with the Finalize/Send button.

Improve wording around finalization

---

docs/_static/css/custom.css

Reducing device screenshot width to 365px from 400px means two can go side-by-side with a screen width of 1500px. Prior to this change, screenshots would always appear vertically stacked on most laptop screens.

Reduce width of device screenshots

---

docs/form-logic.rst
docs/form-repeats.rst

It was previously buried. This moves it closer to where a user might naturally see it and makes it linkable.

Move section about repeat_count value being decreased

---

docs/collect-external-apps.rst

addresses [this discussion on the forum](https://forum.getodk.org/t/should-sub-fields-override-intent-parameters-when-launching-external-app-to-populate-multiple-fields/44109/1)
Adds a warning to describe the parameter clashing problem that external app creators might run into.

Add warning about parameter override for external apps

---

README.md

not sure if this is just me with a broken environment, but my os install is pretty fresh and i couldn't get docs to build without installing `libenchant` natively (`brew install enchant`).
```
sphinx-autobuild -b dirhtml "docs" "docs/_build/html" --re-ignore "central-api|_build"
[sphinx-autobuild] > sphinx-build -b dirhtml /Users/.../code/odk/docs2/docs /Users/.../code/odk/docs2/docs/_build/html
Running Sphinx v7.2.6
Exception occurred:
File "/Users/.../code/odk/docs2/venv/lib/python3.11/site-packages/enchant/_enchant.py", line 79, in from_env_var
assert os.path.exists(library_path), library_path + " does not exist"
AssertionError: /opt/homebrew/lib/libenchant-2.dylib does not exist
The full traceback has been saved in /var/folders/.../.../T/sphinx-err-6gssz1en.log, if you want to report …
```

readme: add note to install enchant natively

---

docs/_static/api-spec/central.yaml

Looks like the functionality was added in https://github.com/getodk/central-backend/commit/c62a7f76833c194f9a16e829d349950cc4d30bce which was released in Central v2023.3.0. It was only added to docs in Central at https://github.com/getodk/central-backend/commit/43474fd09e5e2d0b1ea4c7155078c2d1665dad18 which is not yet released.
It's not a very big deal because the error message is clear but now that we've noticed the issue we might as well fix it.
I have rendered the page.

Add force flag for entity updates

---

docs/xlsform-first-form.rst
docs/xlsform.rst

The XLSX export from Google Sheet is unfortunately not very nice. Also, there are people who don't want to use Google Sheet for various reasons. I think we should always link to both.

Add xlsx tutorial link

---

docs/central-entities.rst
docs/img/central-entities/entity-conflict.png
docs/img/central-entities/entity-table-review.png
docs/img/central-entities/entity-table.png
docs/spelling_wordlist.txt

things that aren't great:
* need to be clearer what happens when updates are made from the entity detail page; what fields are considered "updated" and therefore might cause conflicts? only ones i change?
* missing a couple screenshots
* better example given for conditional update logic.. i just copied the spec and don't understand enough to generate a nicer example than just `true()`
* maybe a diagram showing v1 -> v2/v3 -> v4 branching? not sure it helps

central docs for entity updates

---

docs/central-upgrade.rst

On Slack, @lognaturel wrote about v2023.5:
> We don’t have a PR yet for update instructions. I don’t think there’s anything special for this one
I took a look at the changes on the `next` branch (getodk/central#537), and that sounds right to me. I also took a look at the new database migrations, and I don't see any that should take a long time to run. Given that, I added a line here about how there are no special upgrade notes for .5. We used similar language previously for v1.0 and v1.1.

Add note about v2023.5 to Upgrading Central

---

docs/form-question-types.rst

closes #1707
It documents how to set the minimum number of rows in text questions. We have recently added it in pyxform: https://github.com/XLSForm/pyxform/pull/667

Document setting the minimum number of rows in text questions

---

docs/_static/css/custom.css
docs/central-entities.rst
docs/collect-best-practices.rst
docs/collect-filling-forms.rst
docs/collect-import-export.rst
docs/collect-settings.rst
docs/guide-end-of-form.rst
docs/img/collect-filling-forms/question-screen-exit-popup.png
docs/img/guide-end-of-form/constraint-draft.png
docs/img/guide-end-of-form/reviewer-checklist.png
docs/img/guide-end-of-form/reviewer-code.png
docs/img/guide-end-of-form/reviewer-drafts.png

Some things to consider:
- Do the three sections work well?
- Are the workflow examples enough? Are there other important ones we should highlight?
- Is there enough detail in the suggestions for the workflow examples so that they can be implemented?

Add guide on customizing the end of form experience

---

docs/central-entities.rst
docs/form-audit-log.rst
docs/form-question-types.rst
docs/guide-end-of-form.rst

Thanks for the great feedback, @seadowg and @alyblenkin!
I believe I have addressed all other than:
- did not add image re-enforcing that send and finalize are the same action. I couldn't quickly figure out how to make it flow and I'm not sure we want to draw attention to that distinction, necessarily. Will think about it more.
- did not add a nudge to split the workflow into multiple forms. I couldn't find a great place to put it.

Address review feedback for form end guide

---

docs/xlsform.rst

Inspired by https://forum.getodk.org/t/length-of-value-too-long-for-a-field-error-on-odk-central/44845/2
We should update the form template after merging.

Central limits xmlFormID to 64 chars

---

docs/conf.py

I noticed recently that functions with dashes in their names weren't being correctly linked. It's because we lost https://github.com/getodk/docs/blob/de527759e1507c98f10bfba7102bddaebdd76b16/docs/conf.old.py#L118 when we switched to Furo.
Shoutout to @dgw for [the help](https://github.com/pradyunsg/furo/discussions/767#discussioncomment-8401830)!

Recognize functions with dashes in their names

---

docs/_static/css/custom.css

Add margin above reactions

---

docs/form-styling.rst

closes #1643
I've added a note:

Document that underscores are only treated as markdown when separated by white space

---

docs/build-intro.rst
docs/central-install-digital-ocean.rst
docs/contributing-tips.rst
docs/cygwin.rst
docs/docs-tech-guide.rst
docs/form-question-types.rst
s3_website.yml

Fixing a couple of broken links. We should fix #1766 at some point to make this easier...

Fix ahref recommendations for broken links

---

docs/entities-intro.rst
docs/form-datasets.rst
docs/index.rst

This adds a one-stop-shop document describing Entities conceptually and providing references to other parts of the documentation.
It's organized as Q&A to hopefully make it relatively easy to scan. I considered collapsing the questions and having users expand the ones they want to read but that makes it harder to search the page which I think can be helpful with a document like this.
The questions reflect questions from the forum, Entity office hours, and other conversations with users.
For now, let's introduce this as an orphan page so @yanokwa can do another round of review and we can share with Insiders.
Then, I think it should go at the top of the left table of contents:
That feels like the best spot to me: it's general content that's important to understanding what's possible with …

Add Introduction to Entities

---

docs/central-entities.rst

As discussed in Slack #teams channel 2024-05-23.

add: document limitation that entity properties must be strings

---

docs/form-question-types.rst

closes #1780
This documents the new properties for styling lines and polygons added in https://github.com/getodk/collect/pull/6083

Document styling lines and polygons

---

docs/collect-import-export.rst
docs/collect-offline-maps.rst
docs/collect-sms-submissions.rst
docs/guide-end-of-form.rst
docs/img/collect-offline-maps/layer-access.png
docs/img/collect-offline-maps/select-offline-layer-expanded.png
docs/img/collect-offline-maps/select-offline-layer.png

This page is linked from Collect so it's a common entry point into docs. For this reason, I invested some time to try to make it useful to a broad range of audiences.
I also tried to describe special cases we've considered and make recommendations on how to use the functionality based on some forum conversations.
@alyblenkin and @grzesiek2010 you may want to give this a quick read to see whether I forgot anything.

Update offline maps section for Collect v2024.2

---

docs/collect-filling-forms.rst
docs/collect-settings.rst
docs/img/collect-filling-forms/general-settings-highlight-user-interface.png
docs/img/collect-filling-forms/question-screen-highlight-general-settings.png
docs/img/collect-filling-forms/question-screen-with-buttons.png
docs/img/collect-filling-forms/recover-from-savepoint.png
docs/img/collect-filling-forms/ui-navigation-buttons.png
docs/img/collect-filling-forms/user-interface-highlight-navigation.png

Closes https://github.com/getodk/docs/issues/1463
I decided not to go into very much detail about form versions because I think it mostly works as people expect. I think the one potentially surprising case is if you open form version 4 and there's recovery data that was saved with version 2, the recovery data will be opened with version 2, not version 4 (related to https://github.com/getodk/collect/issues/5947).
@alyblenkin

Describe savepoint recovery

---

docs/central-submissions.rst

As described at https://forum.getodk.org/t/poorly-formatted-csv-export/47980/15
I tried to use the language in the "Import a text file by connecting to it" section at the bottom of https://support.microsoft.com/en-us/office/import-or-export-text-txt-or-csv-files-5250ac4c-663c-47ce-937b-339e391393ba#ID0EBBN=Newer_versions but also use the word "Power Query" as a hint for older versions of Excel.

Text Import Wizard is deprecated

---

docs/central-upgrade.rst

Add Central v2024.2 upgrade instructions

---

docs/central-install-digital-ocean.rst

With an existing install, I can upload a form, preview it, generate a public access link, send in a submission with that link, edit the submission, and it all seems to work. Maybe it’d break with a fresh install, but doubt it. I think we can proceed with removing this warning from the docs.
Our docs say we require Docker v23, but this was Docker v27. Doubt it breaks on v23.
```
root@test:~# lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.6 LTS
Release:	20.04
Codename:	focal
root@test:~#
root@test:~# docker --version && docker compose version
Docker version 27.0.3, build 7d4bcd8
Docker Compose version v2.28.1
root@test:~# ufw status
Status: active
To                         Action      From
--                         ------      ----
22/tcp …
```

Firewall issue no longer happening

---

docs/openrosa-form-list.rst

closes https://github.com/getodk/docs/issues/1852
Happy to iterate on the wording here! I wanted to get across that this isn't for MIME type, it's more about the function of the file.

Add type attribute to manifest document

---

Makefile

> A phony target is one that is not really the name of a file; rather it is just a name for a recipe to be executed when you make an explicit request. There are two reasons to use a phony target: to avoid a conflict with a file of the same name, and to improve performance.
See: https://www.gnu.org/software/make/manual/html_node/Phony-Targets.html

Makefile: mark autobuild target as PHONY

---

docs/central-install-digital-ocean.rst

- I was setting up external S3 for Central today.
- I wanted to test manual syncing using `node lib/bin/s3.js upload-pending 1`.
- The `pgrowlocks` Postgres extension was not installed in the db, causing an error.
- Added the extension to the [Using a custom database](https://docs.getodk.org/central-install-digital-ocean/#using-a-custom-database-server) section during install.
- Referenced the extension install in the [Using S3-compatible storage](https://docs.getodk.org/central-install-digital-ocean/#using-s3-compatible-storage) section, to help users debug if they encounter an error setting this up (linking to the 'Using a custom database' section).

Add info to ensure `pgrowlocks` is installed for S3 on custom DBs

---

docs/central-submissions.rst
docs/central-upgrade.rst
docs/collect-import-export.rst
docs/collect-intro.rst
docs/form-operators-functions.rst
docs/security.rst
docs/spelling_wordlist.txt

Closes https://github.com/getodk/docs/issues/1813
Closes https://github.com/getodk/docs/issues/1795
Related spec pull request: https://github.com/getodk/xforms-spec/pull/321
I also fixed some unrelated issues I saw when running `autobuild`.

Add the geofence function 

---

docs/central-install-digital-ocean.rst

fixes getodk/central#817
Two commits:
- 04e7943 fixes getodk/central#817
- b2082fa simplifies things by removing a step (by cloning the submodules in the same operation as cloning the central repo)

getodk/central#817 : fix redis container umask-at-clone-time sensitivity

---

docs/xlsform.rst

closes #1920 
This pull request documents the usage of the `allow_choice_duplicates` column in the settings sheet.

Document allow_choice_duplicates

---

docs/openrosa-form-submission.rst

It seems unlikely that J2ME is still supported:
* it was renamed Java ME in 2006
* ODK Central recently introduced redirects when using s3 storage
* Collect began supporting redirects at least 5 years ago https://github.com/getodk/collect/blame/0f07d51e8c1bbe34c50f2a47e7c7ad01d0a535e2/collect_app/src/main/java/org/odk/collect/android/openrosa/okhttp/OkHttpOpenRosaServerClientProvider.java#L88 (they may have been supported prior to that)

Drop support for J2ME

---

docs/_static/css/custom.css
docs/central-submissions.rst
docs/form-logic.rst
docs/img/web-forms/calendar-yyyy-mm-dd.png
docs/img/web-forms/geopoint-permission.png
docs/img/web-forms/geopoint-refining-accuracy.png
docs/img/web-forms/image-desktop.png
docs/index.rst
docs/web-forms-intro.rst

Adds a new "Trying ODK Web Forms" page. I'm open to alternative title suggestions. I wanted to make it intriguing and clear that it's experimental. I also wanted to avoid confusion with generic "web forms".
I originally had tried doing a page about generic "web forms" that combined information about Enketo and Web Forms. I got good feedback around that not being future-looking enough so I reworked it to be more focused.
See it at https://output.circle-artifacts.com/output/job/b30c0002-30c3-448f-82aa-98f5b84384d3/artifacts/0/docs/_build/dirhtml/web-forms-intro/index.html and https://output.circle-artifacts.com/output/job/dbef5880-2359-4960-b034-093dbc0d3439/artifacts/0/docs/_build/dirhtml/central-submissions/index.html
Screenshots are placeholders for now to show the general structure of …

Document ODK Web Forms and new way of getting offline-capable Enketo links

---

docs/central-install-digital-ocean.rst

addresses https://github.com/getodk/central/issues/877
<kbd>
Updated documentation

digital-ocean: mention Sentry Tracing

---

.circleci/config.yml

Some Git operations can be difficult when Git LFS is in use and some files aren't pointers when they are expected to be. For example, when I use Git locally on the current `master` branch, I see that the working directory is not clean. Yet `git reset --hard` doesn't fix it:
```
$ git status
On branch master
Changes not staged for commit:
(use "git add <file>..." to update what will be committed)
(use "git restore <file>..." to discard changes in working directory)
modified:   docs/img/form-datasets/instances.png
modified:   docs/img/form-datasets/lookup-expression.png
no changes added to commit (use "git add" and/or "git commit -a")
$ git reset --hard
HEAD is now at 85a432e Update API docs for v2025.1 (#1948)
Encountered 2 files that should have been pointers, but weren't: …
```

Check in CircleCI that Git LFS was used

---

docs/central-install-digital-ocean.rst

Avoid repeating extension names in descriptive text.  This removes ambiguity and the need to update this description every time the list of extensions changes.
Current docs can be seen at https://docs.getodk.org/central-install-digital-ocean/:
closes #
addresses #
https://github.com/getodk/docs/pull/1959/files
None, unless an issue is required as reference for this PR.
Nothing that I know of.
None.

digital-ocean/postgres: clarify extensions documentation

---

docs/form-question-types.rst

closes #1922 
It documents the `hidden-answer` appearance for external string question types.

Document the hidden-answer appearance for external string question types

---

docs/collect-forms.rst
docs/xlsform.rst

Closes https://github.com/getodk/docs/issues/1957
I considered adding some details about the user experience in form lists. Things like:
- every edit will appear separately with the edit count in parentheses
- you can't edit an earlier edit, only the latest one and Collect will prompt for that
- if there's an active draft that's an edit, you can only edit or discard that one, not start a new edit
I decided not to include them because I think there's enough information in Collect to explain these things. Let me know if you think otherwise.
I hesitated on where to put the form design docs. We don't have any details or examples about the settings sheet in the XLSForm page so I thought it worked best where it is even though it's the only piece of form design on that page.

Finalized or sent submissions can be edited

---

README.md
docs/conf.py
docs/openrosa-form-list.rst
docs/openrosa-integrity.md
docs/openrosa.rst
requirements.txt

Adds docs for the spec discussed in [this forum post](https://forum.getodk.org/t/openrosa-spec-proposal-support-offline-entities/48052)
- Specification for `<integrityUrl/>` in the manifest
- A new page detailing the integrity API
I always struggle with using reST, so I added Markdown support using [MyST](https://myst-parser.readthedocs.io/en/latest/). I also had trouble working out how to use the included `Dockerfile`, so I added a note to the `README` about that.

Add documentation for integrity URL

---

docs/guide-end-of-form.rst

closes #1636
I've just updated the [Form states in Collect](https://docs.getodk.org/guide-end-of-form/#form-states-in-collect) section to make it clear that finalized and sent forms can be edited.

Updated the section about editing finalized and sent forms

---

docs/openrosa-form-list.rst

Work towards https://github.com/getodk/collect/issues/6768
This just (hopefully) clarifies that the media file hash does have to represent the contents of the media file itself.

Remove suggestion that hash is MD5 of media file contents

---

docs/_static/js/custom.js

From Kapa's support...
> From looking at the logs I can see that kapa is refusing to answer the user's question because the bot detection mechanism that's used on the widget is flagging the request as possible bot activity. I'm not sure what the exact reason is for this flag – it's usually caused by a VPN or browser extension interfering with the environment, but looking at the forum thread that doesn't seem to apply here. It might be the networking/connectivity issues that's causing reCAPTCHA to incorrectly flag this.
> 
> The only thing that I can think of that might mitigate this would be to change the bot protection mechanism in the widget from Google reCAPTCHA (default) to hCaptcha. This change does not have any drawbacks - in fact, hCaptcha is generally a better solution but we …

Change bot protection to one that works better in poor connections

---

docs/img/web-forms/select-with-images.png
docs/web-forms-intro.rst

Closes https://github.com/getodk/web-forms/issues/501
[See it in action](https://output.circle-artifacts.com/output/job/e163d562-9122-4624-983d-429aa5197882/artifacts/0/docs/_build/dirhtml/web-forms-intro/index.html#selects-with-images)
I described what I remember of the image resizing and quickly double-checked against https://github.com/getodk/web-forms/issues/347 and the all widgets form. It's worth a double check!

Add high-level decription of Web Forms choice images
